/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.components;

import domain.iFrmValue;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JSeparator;

/**
 *
 * @author anakl
 */
public class PanelLRBS extends javax.swing.JPanel implements iFrmValue {

    /**
     * Creates new form PanelLRBS
     */
    public PanelLRBS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        label = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        firstRadioButton = new javax.swing.JRadioButton();
        secondRadioButton = new javax.swing.JRadioButton();

        label.setText("label:");

        buttonGroup1.add(firstRadioButton);
        firstRadioButton.setSelected(true);
        firstRadioButton.setText("firstRadioButton");

        buttonGroup1.add(secondRadioButton);
        secondRadioButton.setText("secondRadioButton");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separator)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(firstRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(secondRadioButton))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(firstRadioButton)
                    .addComponent(secondRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton firstRadioButton;
    private javax.swing.JLabel label;
    private javax.swing.JRadioButton secondRadioButton;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables
 public void setElementText(String labelText, String firstRdbtnText, String secondRdbtnText) {
        label.setText(labelText);
        firstRadioButton.setText(firstRdbtnText);
        secondRadioButton.setText(secondRdbtnText);
    }

    public void clearPanel() {
        this.setValue(true);
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public JRadioButton getFirstRadioButton() {
        return firstRadioButton;
    }

    public void setFirstRadioButton(JRadioButton firstRadioButton) {
        this.firstRadioButton = firstRadioButton;
    }

    public JLabel getLabel() {
        return label;
    }

    public void setLabel(JLabel label) {
        this.label = label;
    }

    public JRadioButton getSecondRadioButton() {
        return secondRadioButton;
    }

    public void setSecondRadioButton(JRadioButton secondRadioButton) {
        this.secondRadioButton = secondRadioButton;
    }

    public JSeparator getSeparator() {
        return separator;
    }

    public void setSeparator(JSeparator separator) {
        this.separator = separator;
    }

    @Override
    public Object getValue() {
        if (firstRadioButton.isSelected()) {
            return firstRadioButton.getText();
        } else {
            return secondRadioButton.getText();
        }
    }

    @Override
    public void setValue(Object object) {
        String value = (String) object;

        if (value.equalsIgnoreCase(firstRadioButton.getText())) {
            firstRadioButton.setSelected(true);
        } else {
            secondRadioButton.setSelected(true);
        }
    }
}
