/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.components;

import domain.iFrmValue;
import events.ClickButtonEvent;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.table.AbstractTableModel;
import listeners.CustomComponentListener;
import listeners.MyTableListener;
import listeners.SearchListener;

/**
 *
 * @author anakl
 */
public class PanelSearch extends javax.swing.JPanel implements iFrmValue, CustomComponentListener {

    private List<SearchListener> searchListeners = new ArrayList<>();
    private List<MyTableListener> myTableListeners = new ArrayList<>();

    /**
     * Creates new form PanelSearch
     */
    public PanelSearch() {
        initComponents();
        formatTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearch = new javax.swing.JPanel();
        panelSearchCriteria = new view.panel.components.PanelTFBS();
        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        panelSearch.setBackground(new java.awt.Color(255, 255, 255));
        panelSearch.setBorder(javax.swing.BorderFactory.createTitledBorder("Search..."));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setFocusable(false);
        table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table.setRowHeight(25);
        table.setSelectionBackground(new java.awt.Color(251, 234, 235));
        table.setShowVerticalLines(false);
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(table);

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchCriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearchCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int selectedRow = table.getSelectedRow();
        clickedTable(selectedRow);
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelSearch;
    private view.panel.components.PanelTFBS panelSearchCriteria;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    public void preparePanel(AbstractTableModel tableModel) {

        panelSearchCriteria.setElementText("Pretraži", "");
        panelSearchCriteria.addListener(this);
        table.setModel(tableModel);
        panelSearchCriteria.setButtonBackground();
    }

    public void clearPanel(AbstractTableModel tableModel) {
        panelSearchCriteria.clearPanel();
        table.setModel(tableModel);
    }

    @Override
    public Object getValue() {
        return table.getSelectedRow();
    }

    @Override
    public void setValue(Object object) {
        AbstractTableModel tableModel = (AbstractTableModel) object;
        table.setModel(tableModel);
    }

    @Override
    public void pressButton(ClickButtonEvent evt) {
        searchListeners.forEach((SearchListener searchListener) -> {
            try {
                AbstractTableModel tableModel = searchListener.searchOdo((String) panelSearchCriteria.getValue());
                table.setModel(tableModel);
                panelSearchCriteria.setValue("");
            } catch (Exception ex) {
                Logger.getLogger(PanelSearch.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    private void clickedTable(int clickedRow) {
        for (MyTableListener myTableListener : myTableListeners) {
            myTableListener.clickedRow(clickedRow);
        }
    }

    public void addListener(SearchListener toAdd) {
        searchListeners.add(toAdd);
    }

    public void addMyTableListener(MyTableListener add) {
        myTableListeners.add(add);
    }

    private void formatTable() {
        table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        table.getTableHeader().setOpaque(false);
        table.getTableHeader().setBackground(new Color(26, 36, 87));
        table.getTableHeader().setForeground(new Color(255, 255, 255));
        table.setRowHeight(25);
    }

    public void setPanelTitle(String value) {
        Border border = BorderFactory.createTitledBorder(value);
        panelSearch.setBorder(border);
    }

    public PanelTFBS getPanelSearchCriteria() {
        return panelSearchCriteria;
    }

    public void setPanelSearchCriteria(PanelTFBS panelSearchCriteria) {
        this.panelSearchCriteria = panelSearchCriteria;
    }

}
