/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialogs;

import controller.CommunicationController;
import domain.DomainObject;
import domain.Karton;
import domain.Radnik;
import domain.Zivotinja;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import listeners.ChooseListener;
import listeners.GenerateListener;
import listeners.MyTableListener;
import view.main.FrmMainWork;

/**
 *
 * @author anakl
 */
public class DialogAddMedicalRecord extends javax.swing.JDialog implements GenerateListener, ChooseListener {

    private Radnik radnik;
    private Zivotinja zivotinja;

    /**
     * Creates new form DialogAddMedicalRecord
     */
    public DialogAddMedicalRecord(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        prepareView();

    }

    public DialogAddMedicalRecord(Radnik radnik) {
        initComponents();
        this.radnik = radnik;
        setLocationRelativeTo(null);
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearchPet = new view.panel.custom.PanelSearchPet();
        panelAddMedicalRecord = new view.panel.custom.PanelAddMedicalRecord();
        btnExit = new javax.swing.JButton();
        btnAddMedicalRecord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodaj karton");

        btnExit.setBackground(new java.awt.Color(47, 60, 127));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Izbriši");
        btnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnExit.setFocusPainted(false);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGroupMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnAddMedicalRecord.setBackground(new java.awt.Color(47, 60, 127));
        btnAddMedicalRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnAddMedicalRecord.setText("Sačuvaj karton");
        btnAddMedicalRecord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAddMedicalRecord.setFocusPainted(false);
        btnAddMedicalRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGroupMouseExited(evt);
            }
        });
        btnAddMedicalRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMedicalRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSearchPet, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAddMedicalRecord, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddMedicalRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAddMedicalRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSearchPet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddMedicalRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        panelAddMedicalRecord.clearPanel();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddMedicalRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedicalRecordActionPerformed
        try {
            Karton karton = (Karton) panelAddMedicalRecord.getValue();
            karton.setZivotinja(zivotinja);
            karton.setRadnik(radnik);
            karton = (Karton) CommunicationController.getInstance().updateDomainObject(karton);
            JOptionPane.showMessageDialog(null, "Sistem je zapamtio novi karton.", "Uspeh",
                    JOptionPane.INFORMATION_MESSAGE);
            panelAddMedicalRecord.clearPanel();
            btnAddMedicalRecord.setEnabled(false);
            btnExit.setEnabled(true);
            ((FrmMainWork) this.getParent()).refreshActivePanel();
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(DialogAddMedicalRecord.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Sistem ne može da zapamti novi karton.","Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddMedicalRecordActionPerformed

    private void btnGroupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGroupMouseEntered
        if (evt.getSource() == btnAddMedicalRecord) {
            btnAddMedicalRecord.setContentAreaFilled(true);
            btnAddMedicalRecord.setBackground(new Color(26, 36, 87));
        }
        if (evt.getSource() == btnExit) {
            btnExit.setContentAreaFilled(true);
            btnExit.setBackground(new Color(26, 36, 87));
        }
    }//GEN-LAST:event_btnGroupMouseEntered

    private void btnGroupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGroupMouseExited
        if (evt.getSource() == btnAddMedicalRecord) {
            btnAddMedicalRecord.setContentAreaFilled(true);
            btnAddMedicalRecord.setBackground(new Color(47, 60, 127));
        }
        if (evt.getSource() == btnAddMedicalRecord) {
            btnExit.setContentAreaFilled(true);
            btnExit.setBackground(new Color(47, 60, 127));
        }
    }//GEN-LAST:event_btnGroupMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMedicalRecord;
    private javax.swing.JButton btnExit;
    private view.panel.custom.PanelAddMedicalRecord panelAddMedicalRecord;
    private view.panel.custom.PanelSearchPet panelSearchPet;
    // End of variables declaration//GEN-END:variables

    @Override
    public DomainObject generateOdo(DomainObject domainObject) throws Exception {
        try {

            DomainObject odo = CommunicationController.getInstance().generateDomainObject(domainObject);

            JOptionPane.showMessageDialog(null, "Sistem je kreirao novi karton","Uspeh", JOptionPane.INFORMATION_MESSAGE);
            btnAddMedicalRecord.setEnabled(true);

            return odo;
        } catch (Exception ex) {
            Logger.getLogger(FrmMainWork.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Sistem ne može da kreira novi karton.","Greška", JOptionPane.ERROR_MESSAGE);
            throw ex;
        }
    }

    private void prepareView() {
        panelAddMedicalRecord.preparePanel();
        panelAddMedicalRecord.getPanelMedicalRecordWorker().setValue(radnik.getRadnikID() + "");
        panelAddMedicalRecord.addListener(this);
        panelSearchPet.preparePanel();
        panelSearchPet.addChooseListener(this);
        panelAddMedicalRecord.setDisabledFields();
        this.getContentPane().setBackground(Color.WHITE);
    }

    @Override
    public void onChooseOdo(DomainObject odo) throws Exception {
        zivotinja = (Zivotinja) odo;
        panelAddMedicalRecord.getPanelMedicalRecordAnimalID().setValue(zivotinja.getZivotinjaID() + "");
        panelAddMedicalRecord.setDisabledFields();
    }

}
