/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialogs;

import controller.CommunicationController;
import domain.Klijent;
import domain.Zivotinja;
import java.awt.Color;
import java.awt.Frame;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import view.main.FrmMainWork;

/**
 *
 * @author anakl
 */
public class DialogEditClient extends javax.swing.JDialog {
    
    private Klijent klijent;

    /**
     * Creates new form DialogEditClient
     */
    public DialogEditClient(java.awt.Frame parent, boolean modal, Klijent klijent) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.klijent = klijent;
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEditClient = new view.panel.custom.PanelEditClient();
        btnExit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        panelSearchClientsPet = new view.panel.custom.PanelSearchClientsPet();
        btnAddAnimal = new javax.swing.JButton();
        btnEditAnimal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Izmeni klijenta");

        panelEditClient.setBorder(javax.swing.BorderFactory.createTitledBorder("Izmeni klijenta"));

        btnExit.setBackground(new java.awt.Color(47, 60, 127));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Odustani");
        btnExit.setFocusPainted(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(47, 60, 127));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Sačuvaj klijenta");
        btnUpdate.setFocusPainted(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAddAnimal.setBackground(new java.awt.Color(47, 60, 127));
        btnAddAnimal.setForeground(new java.awt.Color(255, 255, 255));
        btnAddAnimal.setText("Dodaj životinju");
        btnAddAnimal.setFocusPainted(false);
        btnAddAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAnimalActionPerformed(evt);
            }
        });

        btnEditAnimal.setBackground(new java.awt.Color(47, 60, 127));
        btnEditAnimal.setForeground(new java.awt.Color(255, 255, 255));
        btnEditAnimal.setText("Izmeni životinju");
        btnEditAnimal.setFocusPainted(false);
        btnEditAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEditClient, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelSearchClientsPet, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelEditClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSearchClientsPet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            Klijent klijent = (Klijent) panelEditClient.getValue();
            klijent = (Klijent) CommunicationController.getInstance().updateDomainObject(klijent);
            JOptionPane.showMessageDialog(null, "Uspesno izmenjen klijent " + klijent.getIme()
                    + " " + klijent.getPrezime() + "!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            panelEditClient.clearPanel();
            ((FrmMainWork) this.getParent()).refreshActivePanel();
            dispose();
            
        } catch (Exception ex) {
            Logger.getLogger(DialogAddClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnEditAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAnimalActionPerformed
        Zivotinja zivotinja = (Zivotinja) panelSearchClientsPet.getValue();
        new DialogEditAnimal((Frame) SwingUtilities.getWindowAncestor(this), true, (Zivotinja) panelSearchClientsPet.getValue(), klijent, this).setVisible(true);
    }//GEN-LAST:event_btnEditAnimalActionPerformed

    private void btnAddAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAnimalActionPerformed
        new DialogAddAnimal((Klijent) panelEditClient.getValue()).setVisible(true);
    }//GEN-LAST:event_btnAddAnimalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAnimal;
    private javax.swing.JButton btnEditAnimal;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnUpdate;
    private view.panel.custom.PanelEditClient panelEditClient;
    private view.panel.custom.PanelSearchClientsPet panelSearchClientsPet;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        panelEditClient.preparePanel();
        panelEditClient.setValue(klijent);
        panelSearchClientsPet.preparePanel();
        panelSearchClientsPet.setTableData(klijent.getKlijentID());
        this.getContentPane().setBackground(Color.white);
    }
    
    public void updateTable() throws Exception {
        panelSearchClientsPet.updateTableData(klijent.getKlijentID());
    }
    
}
