/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialogs;

import controller.CommunicationController;
import domain.DomainObject;
import domain.Klijent;
import domain.Zivotinja;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import listeners.GenerateListener;
import view.main.FrmMainWork;

/**
 *
 * @author anakl
 */
public class DialogAddClient extends javax.swing.JDialog implements GenerateListener {

    private Klijent klijent;
    private Zivotinja zivotinja;
    private String activePanel;

    /**
     * Creates new form DialogAddClient
     */
    public DialogAddClient(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        klijent = new Klijent();
        zivotinja = new Zivotinja();
        activePanel = ((FrmMainWork) this.getParent()).getActivePanel();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClearClient = new javax.swing.JButton();
        btnAddClient = new javax.swing.JButton();
        panelAddClient = new view.panel.custom.PanelAddClient();
        panelAddAnimal = new view.panel.custom.PanelAddAnimal();
        btnClearAnimal = new javax.swing.JButton();
        btnAddAnimal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodaj klijenta");
        setBackground(new java.awt.Color(255, 255, 255));

        btnClearClient.setBackground(new java.awt.Color(47, 60, 127));
        btnClearClient.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnClearClient.setForeground(new java.awt.Color(255, 255, 255));
        btnClearClient.setText("Izbriši");
        btnClearClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnClearClient.setFocusPainted(false);
        btnClearClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGroupMouseExited(evt);
            }
        });
        btnClearClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearClientActionPerformed(evt);
            }
        });

        btnAddClient.setBackground(new java.awt.Color(47, 60, 127));
        btnAddClient.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAddClient.setForeground(new java.awt.Color(255, 255, 255));
        btnAddClient.setText("Dodaj klijenta");
        btnAddClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAddClient.setFocusPainted(false);
        btnAddClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGroupMouseExited(evt);
            }
        });
        btnAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClientActionPerformed(evt);
            }
        });

        panelAddClient.setBackground(new java.awt.Color(255, 255, 255));
        panelAddClient.setBorder(javax.swing.BorderFactory.createTitledBorder("Dodaj klijenta"));

        btnClearAnimal.setBackground(new java.awt.Color(47, 60, 127));
        btnClearAnimal.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnClearAnimal.setForeground(new java.awt.Color(255, 255, 255));
        btnClearAnimal.setText("Izbriši");
        btnClearAnimal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnClearAnimal.setFocusPainted(false);
        btnClearAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGroupMouseExited(evt);
            }
        });
        btnClearAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAnimalActionPerformed(evt);
            }
        });

        btnAddAnimal.setBackground(new java.awt.Color(47, 60, 127));
        btnAddAnimal.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAddAnimal.setForeground(new java.awt.Color(255, 255, 255));
        btnAddAnimal.setText("Dodaj životinju");
        btnAddAnimal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAddAnimal.setFocusPainted(false);
        btnAddAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGroupMouseExited(evt);
            }
        });
        btnAddAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddClient, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearClient, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 426, Short.MAX_VALUE)
                        .addComponent(btnAddAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelAddClient, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelAddAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelAddClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAddAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAnimal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearAnimal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearClientActionPerformed
        panelAddClient.clearPanel();
    }//GEN-LAST:event_btnClearClientActionPerformed

    private void btnAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClientActionPerformed
        try {
            klijent = (Klijent) panelAddClient.getValue();
            klijent = (Klijent) CommunicationController.getInstance().updateDomainObject(klijent);
            JOptionPane.showMessageDialog(null, "Uspesno insertovan klijent " + klijent.getIme()
                    + " " + klijent.getPrezime() + "!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);

            panelAddAnimal.getPanelAnimalClientID().setValue(panelAddClient.getPanelClientID().getValue());
            panelAddClient.clearPanel();
            btnAddClient.setEnabled(false);
            btnClearClient.setEnabled(false);
            btnAddAnimal.setEnabled(true);
            btnClearAnimal.setEnabled(true);

        } catch (Exception ex) {
            Logger.getLogger(DialogAddClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddClientActionPerformed

    private void btnClearAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAnimalActionPerformed
        panelAddAnimal.clearPanel();
    }//GEN-LAST:event_btnClearAnimalActionPerformed

    private void btnAddAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAnimalActionPerformed
        try {

            zivotinja = (Zivotinja) panelAddAnimal.getValue();
            zivotinja.setKlijent(klijent);
            zivotinja = (Zivotinja) CommunicationController.getInstance().updateDomainObject(zivotinja);
            JOptionPane.showMessageDialog(null, "Uspesno insertovan ljubimac " + zivotinja.getIme()
                    + "!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            panelAddAnimal.clearPanel();
            btnAddAnimal.setEnabled(false);
            btnClearAnimal.setEnabled(false);
            System.out.println("AKTIVAN PANEL: " + activePanel);
            ((FrmMainWork) this.getParent()).refreshActivePanel();
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(DialogAddClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddAnimalActionPerformed

    private void btnGroupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGroupMouseEntered
        if (evt.getSource() == btnAddAnimal) {
            btnAddAnimal.setContentAreaFilled(true);
            btnAddAnimal.setBackground(new Color(26, 36, 87));
        }
        if (evt.getSource() == btnAddClient) {
            btnAddClient.setContentAreaFilled(true);
            btnAddClient.setBackground(new Color(26, 36, 87));
        }
        if (evt.getSource() == btnClearAnimal) {
            btnClearAnimal.setContentAreaFilled(true);
            btnClearAnimal.setBackground(new Color(26, 36, 87));
        }
        if (evt.getSource() == btnClearClient) {
            btnClearClient.setContentAreaFilled(true);
            btnClearClient.setBackground(new Color(26, 36, 87));
        }
    }//GEN-LAST:event_btnGroupMouseEntered

    private void btnGroupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGroupMouseExited
        if (evt.getSource() == btnAddAnimal) {
            btnAddAnimal.setContentAreaFilled(true);
            btnAddAnimal.setBackground(new Color(47, 60, 127));
        }
        if (evt.getSource() == btnAddClient) {
            btnAddClient.setContentAreaFilled(true);
            btnAddClient.setBackground(new Color(47, 60, 127));
        }
        if (evt.getSource() == btnClearAnimal) {
            btnClearAnimal.setContentAreaFilled(true);
            btnClearAnimal.setBackground(new Color(47, 60, 127));
        }
        if (evt.getSource() == btnClearClient) {
            btnClearClient.setContentAreaFilled(true);
            btnClearClient.setBackground(new Color(47, 60, 127));
        }
    }//GEN-LAST:event_btnGroupMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAnimal;
    private javax.swing.JButton btnAddClient;
    private javax.swing.JButton btnClearAnimal;
    private javax.swing.JButton btnClearClient;
    private view.panel.custom.PanelAddAnimal panelAddAnimal;
    private view.panel.custom.PanelAddClient panelAddClient;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        panelAddClient.preparePanel();
        panelAddClient.addListener(this);
        panelAddAnimal.preparePanel();
        panelAddAnimal.addListener(this);
        this.getContentPane().setBackground(Color.WHITE);
        btnAddAnimal.setEnabled(false);
        btnClearAnimal.setEnabled(false);
    }

    public void clearPanel() {
        panelAddClient.clearPanel();
        panelAddAnimal.clearPanel();
    }

    @Override
    public DomainObject generateOdo(DomainObject domainObject) throws Exception {
        try {

            DomainObject odo = CommunicationController.getInstance().generateDomainObject(domainObject);

            JOptionPane.showMessageDialog(null, "Uspesno generisan " + odo.getTableName() + " !",
                    "Uspeh", JOptionPane.INFORMATION_MESSAGE
            );
            btnAddClient.setEnabled(true);
            btnClearClient.setEnabled(true);

            return odo;
        } catch (Exception ex) {
            Logger.getLogger(FrmMainWork.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }

}
