/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialogs;

import controller.CommunicationController;
import domain.DomainObject;
import domain.Lek;
import domain.PredmetProdaje;
import domain.iFrmValue;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import listeners.GenerateListener;
import view.main.FrmMainWork;

/**
 *
 * @author anakl
 */
public class DialogAddProduct extends javax.swing.JDialog implements iFrmValue, GenerateListener {

    /**
     * Creates new form DialogAddProduct
     */
    public DialogAddProduct(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        prepareView();
    }

    public DialogAddProduct() {
        initComponents();
        setLocationRelativeTo(null);
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAddProduct = new view.panel.custom.PanelAddProduct();
        btnAddProduct = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodaj proizvod");

        btnAddProduct.setBackground(new java.awt.Color(47, 60, 127));
        btnAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProduct.setText("Dodaj proizvod");
        btnAddProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAddProduct.setFocusPainted(false);
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(47, 60, 127));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Odustani");
        btnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnExit.setFocusPainted(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(panelAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        try {
            PredmetProdaje pp = (PredmetProdaje) panelAddProduct.getValue();
            String oznakaLeka = (String) panelAddProduct.getPanelNumberOfProduct().getValue();
            pp = (PredmetProdaje) CommunicationController.getInstance().updateDomainObject(pp);
            Lek lek = new Lek(pp, oznakaLeka, pp.getNaziv());
            lek = (Lek) CommunicationController.getInstance().insertDomainObject(lek);
            JOptionPane.showMessageDialog(null, "Uspesno insertovan predmet prodaje: " + lek.getNaziv()
                    + "!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            panelAddProduct.clearPanel();
            btnAddProduct.setEnabled(false);
            ((FrmMainWork) this.getParent()).refreshActivePanel();
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(DialogAddProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnExit;
    private view.panel.custom.PanelAddProduct panelAddProduct;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        panelAddProduct.preparePanel();
        panelAddProduct.addListener(this);
        this.getContentPane().setBackground(Color.WHITE);
    }

    @Override
    public Object getValue() {
        return panelAddProduct.getValue();
    }

    @Override
    public void setValue(Object object) {
        System.out.println("Not implemented");
    }

    @Override
    public DomainObject generateOdo(DomainObject domainObject) throws Exception {
        try {

            DomainObject odo = CommunicationController.getInstance().generateDomainObject(domainObject);

            JOptionPane.showMessageDialog(null, "Uspesno generisan " + odo.getTableName() + " !",
                    "Uspeh", JOptionPane.INFORMATION_MESSAGE
            );

            btnAddProduct.setEnabled(true);

            return odo;
        } catch (Exception ex) {
            Logger.getLogger(FrmMainWork.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }
}
