/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialogs;

import controller.CommunicationController;
import domain.DomainObject;
import domain.Klijent;
import domain.Zivotinja;
import domain.iFrmValue;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import listeners.GenerateListener;
import view.main.FrmMainWork;
import view.panel.custom.PanelAddAnimal;

/**
 *
 * @author anakl
 */
public class DialogAddAnimal extends javax.swing.JDialog implements iFrmValue, GenerateListener {

    private Klijent klijent;
    private Zivotinja zivotinja;

    /**
     * Creates new form DialogAddAnimal
     */
    public DialogAddAnimal(java.awt.Frame parent, boolean modal, Klijent klijent) {
        super(parent, modal);
        initComponents();
        this.klijent = klijent;
        prepareView();
    }

    public DialogAddAnimal(Klijent klijent) {
        initComponents();
        this.klijent = klijent;
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAddAnimal = new view.panel.custom.PanelAddAnimal();
        btnSavePet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSavePet.setText("Save");
        btnSavePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAddAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSavePet, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAddAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSavePet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSavePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePetActionPerformed
        try {

            zivotinja = (Zivotinja) panelAddAnimal.getValue();
            zivotinja.setKlijent(klijent);
            zivotinja = (Zivotinja) CommunicationController.getInstance().insertDomainObject(zivotinja);
            JOptionPane.showMessageDialog(null, "Uspesno insertovan ljubimac " + zivotinja.getIme()
                    + "!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            panelAddAnimal.clearPanel();
            btnSavePet.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(DialogAddClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSavePetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSavePet;
    private view.panel.custom.PanelAddAnimal panelAddAnimal;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        panelAddAnimal.preparePanel();
        panelAddAnimal.addListener(this);
        panelAddAnimal.getPanelAnimalClientID().setElementText("Sifra klijenta", klijent.getKlijentID() + "");
    }

    @Override
    public Object getValue() {
        return panelAddAnimal.getValue();
    }

    @Override
    public void setValue(Object object) {
        panelAddAnimal.setValue(object);
    }

    @Override
    public DomainObject generateOdo(DomainObject domainObject) throws Exception {
        try {

            DomainObject odo = CommunicationController.getInstance().generateDomainObject(domainObject);

            JOptionPane.showMessageDialog(null, "Uspesno generisan " + odo.getTableName() + " !",
                    "Uspeh", JOptionPane.INFORMATION_MESSAGE
            );

            btnSavePet.setEnabled(true);

            return odo;
        } catch (Exception ex) {
            Logger.getLogger(FrmMainWork.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }

}
