/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialogs;

import controller.ClientController;
import domain.DomainObject;
import domain.Karton;
import java.util.ArrayList;
import java.util.List;
import listeners.ChooseListener;
import listeners.MedicalRecordChooseListener;

/**
 *
 * @author anakl
 */
public class DialogChooseMedicalRecord extends javax.swing.JDialog implements ChooseListener {

    private Karton karton;
    private List<MedicalRecordChooseListener> medicalRecordChooseListeners = new ArrayList<>();

    /**
     * Creates new form DialogChooseMedicalRecord
     */
    public DialogChooseMedicalRecord(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearchMedicalRecords = new view.panel.custom.PanelSearchMedicalRecords();
        btnPotvrdi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnPotvrdi.setText("Potvrdi");
        btnPotvrdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotvrdiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchMedicalRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPotvrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSearchMedicalRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPotvrdi)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPotvrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotvrdiActionPerformed
        chooseMedicalRecord();
        dispose();
    }//GEN-LAST:event_btnPotvrdiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPotvrdi;
    private view.panel.custom.PanelSearchMedicalRecords panelSearchMedicalRecords;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        panelSearchMedicalRecords.preparePanel();
        panelSearchMedicalRecords.addListener(this);
    }

    public void addListener(MedicalRecordChooseListener toAdd) {
        medicalRecordChooseListeners.add(toAdd);
    }

    @Override
    public void onChooseOdo(DomainObject odo) throws Exception {
        karton = (Karton) odo;
    }

    public void chooseMedicalRecord() {
        for (MedicalRecordChooseListener medicalRecordChooseListener : medicalRecordChooseListeners) {
            medicalRecordChooseListener.chooseMedicalRecord(karton);
        }
    }
}
