/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialogs;

import com.sun.jmx.remote.internal.ArrayQueue;
import domain.DomainObject;
import domain.PredmetProdaje;
import domain.StavkaRacuna;
import domain.iFrmValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import listeners.ChooseListener;
import listeners.ItemOfBillChooseListener;

/**
 *
 * @author anakl
 */
public class DialogAddObjectOfSale extends javax.swing.JDialog implements iFrmValue, ChooseListener {

    private BigDecimal totalPriceWithTax = new BigDecimal(0);
    private BigDecimal totalPriceNoTax = new BigDecimal(0);
    private int amount = 0;
    private BigDecimal tax = new BigDecimal(0);
    private PredmetProdaje predmet;
    private List<ItemOfBillChooseListener> itemOfBillChooseListeners = new ArrayList<>();

    /**
     * Creates new form DialogAddObjectOfSale
     */
    public DialogAddObjectOfSale(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prepareView();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearchObjectOfSale = new view.panel.custom.PanelSearchObjectOfSale();
        panelObjectOfSaleName = new view.panel.components.PanelLTFS();
        panelObjectOfSalePriceNoTax = new view.panel.components.PanelLTFS();
        panelObjectOfSalePriceTax = new view.panel.components.PanelLTFS();
        panelObjectOfSaleTax = new view.panel.components.PanelLTFS();
        panelObjectOfSaleAmount = new view.panel.components.PanelLTFS();
        btnClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnClear.setText("Clear");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearchObjectOfSale, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelObjectOfSalePriceTax, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panelObjectOfSaleName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(panelObjectOfSalePriceNoTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelObjectOfSaleTax, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelObjectOfSaleAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelObjectOfSaleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelObjectOfSalePriceNoTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelObjectOfSalePriceTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelObjectOfSaleTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelObjectOfSaleAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelSearchObjectOfSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnAdd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        StavkaRacuna stavkaRacuna = (StavkaRacuna) getValue();
        chooseItemOfBill(stavkaRacuna);
        dispose();
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private view.panel.components.PanelLTFS panelObjectOfSaleAmount;
    private view.panel.components.PanelLTFS panelObjectOfSaleName;
    private view.panel.components.PanelLTFS panelObjectOfSalePriceNoTax;
    private view.panel.components.PanelLTFS panelObjectOfSalePriceTax;
    private view.panel.components.PanelLTFS panelObjectOfSaleTax;
    private view.panel.custom.PanelSearchObjectOfSale panelSearchObjectOfSale;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        panelSearchObjectOfSale.preparePanel();
        panelObjectOfSaleAmount.setElementText("Kolicina", "1");
        panelObjectOfSaleName.setElementText("Naziv", "");
        panelObjectOfSalePriceNoTax.setElementText("Cena bez PDV-a", "");
        panelObjectOfSalePriceTax.setElementText("Cena sa PDV-om", "");
        panelObjectOfSaleTax.setElementText("PDV", "");
        panelObjectOfSaleAmount.setEnabled(true);
        panelObjectOfSaleName.setEnabled(false);
        panelObjectOfSalePriceNoTax.setEnabled(false);
        panelObjectOfSalePriceTax.setEnabled(false);
        panelObjectOfSaleTax.setEnabled(false);
        panelSearchObjectOfSale.addChooseListener(this);
    }

    @Override
    public Object getValue() {
        StavkaRacuna sr = new StavkaRacuna();
        totalPriceNoTax = new BigDecimal((String) panelObjectOfSalePriceNoTax.getValue());
        totalPriceWithTax = new BigDecimal((String) panelObjectOfSalePriceTax.getValue());
        amount = Integer.parseInt((String) panelObjectOfSaleAmount.getValue());
        tax = new BigDecimal((String) panelObjectOfSaleTax.getValue());
        sr.setCenaPoJediniciBezPoreza(totalPriceNoTax);
        sr.setCenaPoJediniciSaPorezom(totalPriceWithTax);
        sr.setKolicina(amount);
        sr.setPredmetProdaje((PredmetProdaje) panelSearchObjectOfSale.getValue());
        sr.setUkupnaCenaBezPoreza(totalPriceNoTax.multiply(BigDecimal.valueOf(amount)));
        sr.setUkupnaCenaSaPorezom(totalPriceWithTax.multiply(BigDecimal.valueOf(amount)));
        return sr;
    }

    @Override
    public void setValue(Object object) {
        PredmetProdaje pp = (PredmetProdaje) object;
        panelObjectOfSaleName.setValue(pp.getNaziv());
        panelObjectOfSalePriceNoTax.setValue(pp.getCenaBezPoreza() + "");
        panelObjectOfSalePriceTax.setValue(pp.getCenaSaPorezom());
        panelObjectOfSaleTax.setValue(pp.getPoreskaStopa());

    }

    public void clearPanel() {
        panelObjectOfSaleAmount.clearPanel();
        panelObjectOfSaleName.clearPanel();
        panelObjectOfSalePriceNoTax.clearPanel();
        panelObjectOfSalePriceTax.clearPanel();
        panelObjectOfSaleTax.clearPanel();
        prepareView();
    }

    public void addListener(ItemOfBillChooseListener toAdd) {
        itemOfBillChooseListeners.add(toAdd);
    }

    @Override
    public void onChooseOdo(DomainObject odo) throws Exception {
        predmet = (PredmetProdaje) odo;
        panelObjectOfSaleName.setValue(predmet.getNaziv());
        panelObjectOfSalePriceNoTax.setValue(predmet.getCenaBezPoreza() + "");
        panelObjectOfSalePriceTax.setValue(predmet.getCenaSaPorezom() + "");
        panelObjectOfSaleTax.setValue(predmet.getPoreskaStopa().getVrednost() + "");
    }

    public void chooseItemOfBill(StavkaRacuna stavkaRacuna) {
        for (ItemOfBillChooseListener itemOfBillChooseListener : itemOfBillChooseListeners) {
            itemOfBillChooseListener.onChooseItemOfBill(stavkaRacuna);
        }
    }
}
