/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialogs;

import controller.CommunicationController;
import domain.DomainObject;
import domain.Radnik;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import listeners.GenerateListener;
import view.main.FrmMainWork;

/**
 *
 * @author anakl
 */
public class DialogAddWorker extends javax.swing.JDialog implements GenerateListener {

    private Radnik radnik;

    /**
     * Creates new form DialogAddWorker
     */
    public DialogAddWorker(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        radnik = new Radnik();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAddWorker = new view.panel.custom.PanelAddWorker();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodaj radnika");

        btnAdd.setBackground(new java.awt.Color(47, 60, 127));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Dodaj radnika");
        btnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAdd.setFocusPainted(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(47, 60, 127));
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Izbriši");
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnClear.setFocusPainted(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAddWorker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAddWorker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            radnik = (Radnik) panelAddWorker.getValue();
            radnik = (Radnik) CommunicationController.getInstance().updateDomainObject(radnik);
            JOptionPane.showMessageDialog(null, "Uspesno insertovan radnik " + radnik.getIme()
                    + " " + radnik.getPrezime() + "!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);

            panelAddWorker.clearPanel();
            btnAdd.setEnabled(false);
            btnClear.setEnabled(false);
            ((FrmMainWork) this.getParent()).refreshActivePanel();
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(DialogAddClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        panelAddWorker.clearPanel();
    }//GEN-LAST:event_btnClearActionPerformed

    private void prepareView() {
        panelAddWorker.preparePanel();
        panelAddWorker.addListener(this);
        this.getContentPane().setBackground(Color.WHITE);
    }

    public void clearPanel() {
        panelAddWorker.clearPanel();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private view.panel.custom.PanelAddWorker panelAddWorker;
    // End of variables declaration//GEN-END:variables

    @Override
    public DomainObject generateOdo(DomainObject domainObject) throws Exception {
        try {

            DomainObject odo = CommunicationController.getInstance().generateDomainObject(domainObject);

            JOptionPane.showMessageDialog(null, "Uspesno generisan " + odo.getTableName() + " !",
                    "Uspeh", JOptionPane.INFORMATION_MESSAGE
            );
            btnAdd.setEnabled(true);
            btnClear.setEnabled(true);

            return odo;
        } catch (Exception ex) {
            Logger.getLogger(FrmMainWork.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }
}
