/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialogs;

import controller.CommunicationController;
import domain.DomainObject;
import domain.Klijent;
import domain.Zivotinja;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import listeners.GenerateListener;
import view.main.FrmMainWork;

/**
 *
 * @author anakl
 */
public class DialogAddClient extends javax.swing.JDialog implements GenerateListener {

    private Klijent klijent;
    private Zivotinja zivotinja;

    /**
     * Creates new form DialogAddClient
     */
    public DialogAddClient(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        klijent = new Klijent();
        zivotinja = new Zivotinja();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClearClient = new javax.swing.JButton();
        btnAddClient = new javax.swing.JButton();
        panelAddClient = new view.panel.custom.PanelAddClient();
        panelAddAnimal = new view.panel.custom.PanelAddAnimal();
        btnClearAnimal = new javax.swing.JButton();
        btnAddAnimal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        btnClearClient.setText("Clear");
        btnClearClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearClientActionPerformed(evt);
            }
        });

        btnAddClient.setText("Add");
        btnAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClientActionPerformed(evt);
            }
        });

        panelAddClient.setBorder(javax.swing.BorderFactory.createTitledBorder("Add client"));

        btnClearAnimal.setText("Clear");
        btnClearAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAnimalActionPerformed(evt);
            }
        });

        btnAddAnimal.setText("Add");
        btnAddAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddClient, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearClient, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 466, Short.MAX_VALUE)
                        .addComponent(btnAddAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelAddClient, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelAddAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelAddClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAddAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddClient)
                    .addComponent(btnClearClient)
                    .addComponent(btnClearAnimal)
                    .addComponent(btnAddAnimal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearClientActionPerformed
        panelAddClient.clearPanel();
    }//GEN-LAST:event_btnClearClientActionPerformed

    private void btnAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClientActionPerformed
        try {
            klijent = (Klijent) panelAddClient.getValue();
            klijent = (Klijent) CommunicationController.getInstance().updateDomainObject(klijent);
            JOptionPane.showMessageDialog(null, "Uspesno insertovan klijent " + klijent.getIme()
                    + " " + klijent.getPrezime() + "!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            panelAddAnimal.getPanelAnimalClientID().setValue(panelAddClient.getPanelClientID().getValue());
            panelAddClient.clearPanel();
            btnAddClient.setEnabled(false);
            btnClearClient.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(DialogAddClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddClientActionPerformed

    private void btnClearAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAnimalActionPerformed
        panelAddAnimal.clearPanel();
    }//GEN-LAST:event_btnClearAnimalActionPerformed

    private void btnAddAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAnimalActionPerformed
        try {

            zivotinja = (Zivotinja) panelAddAnimal.getValue();
            zivotinja.setKlijent(klijent);
            zivotinja = (Zivotinja) CommunicationController.getInstance().updateDomainObject(zivotinja);
            JOptionPane.showMessageDialog(null, "Uspesno insertovan ljubimac " + zivotinja.getIme()
                    + "!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            panelAddAnimal.clearPanel();
            btnAddAnimal.setEnabled(false);
            btnClearAnimal.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(DialogAddClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddAnimalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAnimal;
    private javax.swing.JButton btnAddClient;
    private javax.swing.JButton btnClearAnimal;
    private javax.swing.JButton btnClearClient;
    private view.panel.custom.PanelAddAnimal panelAddAnimal;
    private view.panel.custom.PanelAddClient panelAddClient;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        panelAddClient.preparePanel();
        panelAddClient.addListener(this);
        panelAddAnimal.preparePanel();
        panelAddAnimal.addListener(this);
    }

    public void clearPanel() {
        panelAddClient.clearPanel();
        panelAddAnimal.clearPanel();
    }

    @Override
    public DomainObject generateOdo(DomainObject domainObject) throws Exception {
        try {

            DomainObject odo = CommunicationController.getInstance().generateDomainObject(domainObject);
            
            JOptionPane.showMessageDialog(null, "Uspesno generisan " + odo.getTableName()+" !",
                    "Uspeh", JOptionPane.INFORMATION_MESSAGE
            );
            btnAddClient.setEnabled(true);
            btnClearClient.setEnabled(true);

            return odo;
        } catch (Exception ex) {
            Logger.getLogger(FrmMainWork.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }

}
