/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialogs;

import controller.CommunicationController;
import domain.DomainObject;
import domain.Racun;
import domain.Radnik;
import domain.StavkaRacuna;
import java.awt.Color;
import java.awt.Frame;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import listeners.GenerateListener;
import listeners.ItemOfBillChooseListener;
import view.main.FrmMainWork;
import view.panel.custom.PanelSearchMedicalRecords;
import view.tableModels.TableModelStavkaRacuna;

/**
 *
 * @author anakl
 */
public class DialogAddBill extends javax.swing.JDialog implements GenerateListener, ItemOfBillChooseListener {
    
    private Racun racun;
    private StavkaRacuna stavka;
    private Radnik radnik;
    private List<StavkaRacuna> stavkeRacuna;
    private TableModelStavkaRacuna tmsr;
    private DialogAddObjectOfSale dialogAddObjectOfSale;
    private BigDecimal totalPriceWithTax = new BigDecimal(0);
    private BigDecimal totalPriceNoTax = new BigDecimal(0);

    /**
     * Creates new form DialogAddBill
     */
    public DialogAddBill(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        stavkeRacuna = new ArrayList<>();
        racun = new Racun();
        stavka = new StavkaRacuna();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAddBill = new view.panel.custom.PanelAddBill();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBillItems = new javax.swing.JTable();
        btnAddItem = new javax.swing.JButton();
        btnClearItem = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodaj račun");
        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        tableBillItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableBillItems);

        btnAddItem.setBackground(new java.awt.Color(47, 60, 127));
        btnAddItem.setForeground(new java.awt.Color(255, 255, 255));
        btnAddItem.setText("Dodaj stavku");
        btnAddItem.setBorderPainted(false);
        btnAddItem.setFocusPainted(false);
        btnAddItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGroupMouseExited(evt);
            }
        });
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnClearItem.setBackground(new java.awt.Color(47, 60, 127));
        btnClearItem.setForeground(new java.awt.Color(255, 255, 255));
        btnClearItem.setText("Izbriši stavku");
        btnClearItem.setBorderPainted(false);
        btnClearItem.setFocusPainted(false);
        btnClearItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGroupMouseExited(evt);
            }
        });
        btnClearItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearItemActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(47, 60, 127));
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Obriši račun");
        btnClear.setBorderPainted(false);
        btnClear.setFocusPainted(false);
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGroupMouseExited(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(47, 60, 127));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Sačuvaj račun");
        btnAdd.setBorderPainted(false);
        btnAdd.setFocusPainted(false);
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGroupMouseExited(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAddBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearItem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAddBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        dialogAddObjectOfSale = new DialogAddObjectOfSale((Frame) SwingUtilities.getWindowAncestor(SwingUtilities.getWindowAncestor(this)), true);
        dialogAddObjectOfSale.addListener(this);
        dialogAddObjectOfSale.setVisible(true);
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnClearItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearItemActionPerformed
        int rowSelected = tableBillItems.getSelectedRow();
        totalPriceNoTax = new BigDecimal(panelAddBill.getPanelBillTotalPriceNoTax().getValue() + "");
        totalPriceWithTax = new BigDecimal(panelAddBill.getPanelBillTotalPriceTax().getValue() + "");
        totalPriceNoTax = totalPriceNoTax.subtract(stavkeRacuna.get(rowSelected).getUkupnaCenaBezPoreza());
        totalPriceWithTax = totalPriceWithTax.subtract(stavkeRacuna.get(rowSelected).getUkupnaCenaSaPorezom());
        
        panelAddBill.getPanelBillTotalPriceNoTax().setValue(totalPriceNoTax + "");
        panelAddBill.getPanelBillTotalPriceTax().setValue(totalPriceWithTax + "");
        if (rowSelected != -1) {
            stavkeRacuna.remove(rowSelected);
            tmsr.azuriraj(stavkeRacuna);
        }
    }//GEN-LAST:event_btnClearItemActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            racun = (Racun) panelAddBill.getValue();
            TableModelStavkaRacuna model = (TableModelStavkaRacuna) tableBillItems.getModel();
            List<StavkaRacuna> stavkeRacuna = model.getAllInvoiceItems();
            racun.setStavkeRacuna(stavkeRacuna);
            racun.setObradjen(true);
            racun = CommunicationController.getInstance().saveBillWithItems(racun);

            //CommunicationController.getInstance().updateDomainObject(racun);
            //CommunicationController.getInstance().insertListDomainObject(stavkeRacuna);
            JOptionPane.showMessageDialog(null, "Sistem je zapamtio novi račun", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            clearPanel();
            ((FrmMainWork) this.getParent()).refreshActivePanel();
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(DialogAddBill.class.getName()).log(Level.SEVERE, null, ex);
            racun.setObradjen(false);
            JOptionPane.showMessageDialog(null, "Sistem ne može da zapamti novi račun", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearPanel();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnGroupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGroupMouseEntered
        if (evt.getSource() == btnAdd) {
            btnAdd.setContentAreaFilled(true);
            btnAdd.setBackground(new Color(26, 36, 87));
        }
        if (evt.getSource() == btnAddItem) {
            btnAddItem.setContentAreaFilled(true);
            btnAddItem.setBackground(new Color(26, 36, 87));
        }
        if (evt.getSource() == btnClear) {
            btnClear.setContentAreaFilled(true);
            btnClear.setBackground(new Color(26, 36, 87));
        }
        if (evt.getSource() == btnClearItem) {
            btnClearItem.setContentAreaFilled(true);
            btnClearItem.setBackground(new Color(26, 36, 87));
        }
    }//GEN-LAST:event_btnGroupMouseEntered

    private void btnGroupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGroupMouseExited
        if (evt.getSource() == btnAdd) {
            btnAdd.setContentAreaFilled(true);
            btnAdd.setBackground(new Color(47, 60, 127));
        }
        if (evt.getSource() == btnAddItem) {
            btnAddItem.setContentAreaFilled(true);
            btnAddItem.setBackground(new Color(47, 60, 127));
        }
        if (evt.getSource() == btnClear) {
            btnClear.setContentAreaFilled(true);
            btnClear.setBackground(new Color(47, 60, 127));
        }
        if (evt.getSource() == btnClearItem) {
            btnClearItem.setContentAreaFilled(true);
            btnClearItem.setBackground(new Color(47, 60, 127));
        }
    }//GEN-LAST:event_btnGroupMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private view.panel.custom.PanelAddBill panelAddBill;
    private javax.swing.JTable tableBillItems;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        tmsr = new TableModelStavkaRacuna(stavkeRacuna);
        tableBillItems.setModel(tmsr);
        panelAddBill.preparePanel();
        panelAddBill.addListener(this);
        this.getContentPane().setBackground(Color.WHITE);
        panelAddBill.getPanelBillTotalPriceNoTax().setDisabledField();
        panelAddBill.getPanelBillTotalPriceTax().setDisabledField();
    }
    
    public void clearPanel() {
        panelAddBill.clearPanel();
        stavkeRacuna.clear();
        tmsr.azuriraj(stavkeRacuna);
    }
    
    @Override
    public DomainObject generateOdo(DomainObject domainObject) throws Exception {
        try {
            DomainObject odo = CommunicationController.getInstance().generateDomainObject(domainObject);
            
            JOptionPane.showMessageDialog(null, "Sistem je kreirao novi račun.", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            btnAdd.setEnabled(true);
            btnClear.setEnabled(true);
            
            return odo;
        } catch (Exception ex) {
            Logger.getLogger(FrmMainWork.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Sistem ne može da kreira novi račun.", "Greška", JOptionPane.ERROR_MESSAGE);
            throw ex;
        }
    }
    
    @Override
    public void onChooseItemOfBill(StavkaRacuna stavkaRacuna) {
        stavkaRacuna.setStavkaRacunaID(Long.valueOf(stavkeRacuna.size() + 1));
        Racun racun = (Racun) panelAddBill.getValue();
        racun.setUkupnaCenaBezPoreza(racun.getUkupnaCenaBezPoreza().add(stavkaRacuna.getUkupnaCenaBezPoreza()));
        racun.setUkupnaCenaSaPorezom(racun.getUkupnaCenaSaPorezom().add(stavkaRacuna.getUkupnaCenaSaPorezom()));
        panelAddBill.setValue(racun);
        stavkaRacuna.setRacun(racun);
        stavkeRacuna.add(stavkaRacuna);
        tmsr.azuriraj(stavkeRacuna);
    }
    
}
