/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialogs;

import controller.CommunicationController;
import domain.Klijent;
import domain.Zivotinja;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import view.main.FrmLoginClient;
import view.main.FrmMainWork;

/**
 *
 * @author anakl
 */
public class DialogEditAnimal extends javax.swing.JDialog {

    private Zivotinja zivotinja;
    private Klijent klijent;
    private DialogEditClient dialogEditClient;

    /**
     * Creates new form DialogEditAnimal
     */
    public DialogEditAnimal(java.awt.Frame parent, boolean modal, Zivotinja zivotinja, Klijent klijent, DialogEditClient dialogEditClient) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.zivotinja = zivotinja;
        this.klijent = klijent;
        this.dialogEditClient = dialogEditClient;
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEditAnimal = new view.panel.custom.PanelEditAnimal();
        btnSaveAnimal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Izmeni životinju");

        btnSaveAnimal.setBackground(new java.awt.Color(47, 60, 127));
        btnSaveAnimal.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveAnimal.setText("Sačuvaj");
        btnSaveAnimal.setFocusPainted(false);
        btnSaveAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSaveAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEditAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEditAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAnimalActionPerformed
        try {
            Zivotinja zivotinja = (Zivotinja) panelEditAnimal.getValue();
            zivotinja.setKlijent(klijent);
            zivotinja = (Zivotinja) CommunicationController.getInstance().updateDomainObject(zivotinja);
            JOptionPane.showMessageDialog(null, "Uspesno izmenjen ljubimac " + zivotinja.getIme()
                    + "!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);

            panelEditAnimal.clearPanel();
            btnSaveAnimal.setEnabled(false);
            dialogEditClient.updateTable();
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(DialogEditAnimal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveAnimalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveAnimal;
    private view.panel.custom.PanelEditAnimal panelEditAnimal;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        panelEditAnimal.preparePanel();
        panelEditAnimal.setValue(zivotinja);
        this.getContentPane().setBackground(Color.WHITE);
    }

}
