/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.custom;

import domain.DomainObject;
import domain.Klijent;
import domain.iFrmValue;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import listeners.GenerateListener;

/**
 *
 * @author anakl
 */
public class PanelEditClient extends javax.swing.JPanel implements iFrmValue {

    /**
     * Creates new form PanelEditClient
     */
    public PanelEditClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelClientID = new view.panel.components.PanelLTFS();
        panelClientName = new view.panel.components.PanelLTFS();
        panelClientSurname = new view.panel.components.PanelLTFS();
        panelClientAddress = new view.panel.components.PanelLTFS();
        panelClientTelephone = new view.panel.components.PanelLTFS();
        panelClientCity = new view.panel.components.PanelLTFS();
        panelClientBirthdate = new view.panel.components.PanelLDPS();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Izmeni klijenta"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelClientID, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(panelClientName, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(panelClientSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(panelClientAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(panelClientTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(panelClientCity, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(panelClientBirthdate, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelClientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelClientSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelClientBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(panelClientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelClientTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelClientCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panel.components.PanelLTFS panelClientAddress;
    private view.panel.components.PanelLDPS panelClientBirthdate;
    private view.panel.components.PanelLTFS panelClientCity;
    private view.panel.components.PanelLTFS panelClientID;
    private view.panel.components.PanelLTFS panelClientName;
    private view.panel.components.PanelLTFS panelClientSurname;
    private view.panel.components.PanelLTFS panelClientTelephone;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        
        panelClientID.getTextField().setEnabled(false);
        panelClientID.setElementText("Šifra klijenta", "");
        panelClientAddress.setElementText("Adresa", "");
        panelClientBirthdate.setElementText("Datum rođenja", new Date());
        panelClientCity.setElementText("Grad", "");
        panelClientName.setElementText("Ime", "");
        panelClientSurname.setElementText("Prezime", "");
        panelClientTelephone.setElementText("Telefon", "");
    }
    
    @Override
    public Object getValue() {
        Long id = new Long((String) panelClientID.getValue());
        String name = (String) panelClientName.getValue();
        String surname = (String) panelClientSurname.getValue();
        String address = (String) panelClientAddress.getValue();
        String telephone = (String) panelClientTelephone.getValue();
        String city = (String) panelClientCity.getValue();
        Date birthdate = (Date) panelClientBirthdate.getValue();
        Klijent klijent = new Klijent(id, name, surname, birthdate, address, city, telephone);
        return klijent;
    }
    
    @Override
    public void setValue(Object object) {
        Klijent klijent = (Klijent) object;
        panelClientID.setValue(klijent.getKlijentID() + "");
        panelClientName.setValue(klijent.getIme());
        panelClientSurname.setValue(klijent.getPrezime());
        panelClientCity.setValue(klijent.getAdresa());
        panelClientTelephone.setValue(klijent.getTelefon());
        panelClientAddress.setValue(klijent.getAdresa());
        panelClientBirthdate.setValue(klijent.getDatumRodjenja());
    }
    
    public void clearPanel() {
        panelClientID.clearPanel();
        panelClientAddress.clearPanel();
        panelClientCity.clearPanel();
        panelClientName.clearPanel();
        panelClientSurname.clearPanel();
        panelClientTelephone.clearPanel();
        panelClientBirthdate.clearPanel();
    }
}
