/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.custom;

import domain.BojaZivotinja;
import domain.DomainObject;
import domain.Klijent;
import domain.RasaMacke;
import domain.VrstaZivotinje;
import domain.Zivotinja;
import domain.iFrmValue;
import events.ClickButtonEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import listeners.CustomComponentListener;
import listeners.GenerateListener;
import view.panel.components.PanelLTFS;

/**
 *
 * @author anakl
 */
public class PanelAddAnimal extends javax.swing.JPanel implements iFrmValue, CustomComponentListener {

    private List<GenerateListener> generateListeners = new ArrayList<>();
    private Klijent klijent;

    /**
     * Creates new form PanelAddAnimal
     */
    public PanelAddAnimal(Klijent klijent) {
        initComponents();
        this.klijent = klijent;
    }

    public PanelAddAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAnimalID = new view.panel.components.PanelLTFBS();
        panelAnimalName = new view.panel.components.PanelLTFS();
        panelAnimalBreed = new view.panel.components.PanelLCBS();
        panelAnimalColor = new view.panel.components.PanelLCBS();
        panelAnimalGender = new view.panel.components.PanelLRBS();
        panelAnimalDate = new view.panel.components.PanelLDPS();
        panelAnimalClientID = new view.panel.components.PanelLTFS();
        panelAnimalType = new view.panel.components.PanelLCBS();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Add pet"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAnimalID, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addComponent(panelAnimalName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAnimalBreed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAnimalColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAnimalGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAnimalDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAnimalClientID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAnimalType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAnimalID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAnimalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAnimalBreed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAnimalColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAnimalGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAnimalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAnimalClientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAnimalType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panel.components.PanelLCBS panelAnimalBreed;
    private view.panel.components.PanelLTFS panelAnimalClientID;
    private view.panel.components.PanelLCBS panelAnimalColor;
    private view.panel.components.PanelLDPS panelAnimalDate;
    private view.panel.components.PanelLRBS panelAnimalGender;
    private view.panel.components.PanelLTFBS panelAnimalID;
    private view.panel.components.PanelLTFS panelAnimalName;
    private view.panel.components.PanelLCBS panelAnimalType;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        panelAnimalID.addListener(this);
        panelAnimalID.getTextField().setEnabled(false);
        panelAnimalID.setElementText("Generisi", "Sifra zivotinje", "");
        panelAnimalName.setElementText("Ime", "");
        panelAnimalDate.setElementText("Datum rodjenja", new Date());
        panelAnimalBreed.setElementText("Rasa", new DefaultComboBoxModel<>(RasaMacke.values()));
        panelAnimalGender.setElementText("Pol", "Zenski", "Muski");
        panelAnimalType.setElementText("Vrsta", new DefaultComboBoxModel<>(VrstaZivotinje.values()));
        panelAnimalColor.setElementText("Boja", new DefaultComboBoxModel<>(BojaZivotinja.values()));
        panelAnimalClientID.setElementText("Sifra klijenta", "");
        panelAnimalClientID.getTextField().setEnabled(false);
    }

    public void clearPanel() {
        panelAnimalID.clearPanel();
        panelAnimalName.clearPanel();
        panelAnimalDate.clearPanel();
        panelAnimalBreed.clearPanel();
        panelAnimalGender.clearPanel();
        panelAnimalType.clearPanel();
        panelAnimalColor.clearPanel();
        panelAnimalClientID.clearPanel();
    }

    @Override
    public Object getValue() {
        Long id = new Long((String) panelAnimalID.getValue());
        String name = (String) panelAnimalName.getValue();
        String breed = String.valueOf(panelAnimalBreed.getValue());
        String type = String.valueOf(panelAnimalType.getValue());
        String color = String.valueOf(panelAnimalColor.getValue());
        String gender = String.valueOf(panelAnimalGender.getValue());
        Date birthdate = (Date) panelAnimalDate.getValue();
        Zivotinja zivotinja = new Zivotinja(id, name, breed, type, color, gender, birthdate, klijent);
        return zivotinja;
    }

    @Override
    public void setValue(Object object) {
        Zivotinja zivotinja = (Zivotinja) object;
        panelAnimalBreed.setValue(zivotinja.getZivotinjaID() + "");
        panelAnimalClientID.setValue(zivotinja.getKlijent().getKlijentID());
        panelAnimalType.setValue(zivotinja.getVrsta());
        panelAnimalGender.setValue(zivotinja.getPol());
        panelAnimalName.setValue(zivotinja.getIme());
        panelAnimalDate.setValue(zivotinja.getDatumRodjenja());
        panelAnimalColor.setValue(zivotinja.getBoja());
        panelAnimalID.setValue(zivotinja.getZivotinjaID());
    }

    public void addListener(GenerateListener toAdd) {
        generateListeners.add(toAdd);
    }

    @Override
    public void pressButton(ClickButtonEvent evt) {
        for (GenerateListener generateListener : generateListeners) {
            try {

                DomainObject odo = generateListener.generateOdo(new Zivotinja());

                panelAnimalID.setValue(odo.getObjectIDValue() + "");
            } catch (Exception ex) {
                Logger.getLogger(PanelAddClient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public PanelLTFS getPanelAnimalClientID() {
        return panelAnimalClientID;
    }

    public void setPanelAnimalClientID(PanelLTFS panelAnimalClientID) {
        this.panelAnimalClientID = panelAnimalClientID;
    }

}
