/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.custom;

import controller.CommunicationController;
import domain.DomainObject;
import domain.Racun;
import domain.iFrmValue;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.AbstractTableModel;
import listeners.DeleteObjectListener;
import listeners.MyTableListener;
import listeners.SearchListener;
import listeners.TableDataListener;
import view.tableModels.TableModelRacun;

/**
 *
 * @author anakl
 */
public class PanelSearchBill extends javax.swing.JPanel implements TableDataListener, DeleteObjectListener, SearchListener, MyTableListener, iFrmValue {

    private TableModelRacun tmr;
    private List<Racun> racuni;
    private Racun racun;

    /**
     * Creates new form PanelSearchBill
     */
    public PanelSearchBill() {
        initComponents();
        racuni = new ArrayList<>();
        racun = new Racun();
        fillTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearchBill = new view.panel.components.PanelSearch();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchBill, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panel.components.PanelSearch panelSearchBill;
    // End of variables declaration//GEN-END:variables
 public void preparePanel() {
        tmr = new TableModelRacun(racuni);
        panelSearchBill.preparePanel(tmr);
        panelSearchBill.addListener(this);
        panelSearchBill.addMyTableListener(this);
        panelSearchBill.setPanelTitle("Pretraži račune");
    }

    public void clearPanel() {
        racuni.clear();
        panelSearchBill.clearPanel(new TableModelRacun(racuni));
    }

    @Override
    public AbstractTableModel searchOdo(String criteria) throws Exception {
        try {
//            klijenti = CommunicationController.getInstance().searchClientsWithCriteria(criteria);
//            JOptionPane.showMessageDialog(this, "Uspesno vraceni klijenti!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            racuni = CommunicationController.getInstance().selectAllBills();
            return new TableModelRacun(racuni);
        } catch (Exception ex) {
            Logger.getLogger(PanelSearchClient.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }

    private void fillTableData() {
        try {
            racuni = CommunicationController.getInstance().selectAllBills();
            new TableModelRacun(racuni);
        } catch (Exception ex) {
            Logger.getLogger(PanelSearchClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void clickedRow(int clickedRow) {
        racun = tmr.getBill(clickedRow);
    }

    @Override
    public Object getValue() {
        return racun;
    }

    @Override
    public void setValue(Object object) {
        this.racun = (Racun) object;
    }

    @Override
    public void removeObject(DomainObject odo) throws Exception {
        racun = (Racun) getValue();
        CommunicationController.getInstance().deleteObject(racun);
        racuni = CommunicationController.getInstance().selectAllBills();
        tmr.azuriraj(racuni);

    }

    public void updateTable() throws Exception {
        racuni = CommunicationController.getInstance().selectAllBills();
        tmr.azuriraj(racuni);
    }

}
