/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.custom;

import domain.DomainObject;
import domain.Radnik;
import domain.iFrmValue;
import events.ClickButtonEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import listeners.CustomComponentListener;
import listeners.GenerateListener;

/**
 *
 * @author anakl
 */
public class PanelAddWorker extends javax.swing.JPanel implements iFrmValue, CustomComponentListener {

    private List<GenerateListener> generateListeners = new ArrayList<>();

    /**
     * Creates new form PanelAddWorker
     */
    public PanelAddWorker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWorkerID = new view.panel.components.PanelLTFBS();
        panelWorkerName = new view.panel.components.PanelLTFS();
        panelWorkerSurname = new view.panel.components.PanelLTFS();
        panelWorkerBirthdate = new view.panel.components.PanelLDPS();
        panelWorkerAddress = new view.panel.components.PanelLTFS();
        panelWorkerTelephone = new view.panel.components.PanelLTFS();
        panelWorkerAdmin = new view.panel.components.PanelLRBS();
        panelWorkerUsername = new view.panel.components.PanelLTFS();
        panelWorkerPassword = new view.panel.components.PanelLTFS();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Add worker"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelWorkerID, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addComponent(panelWorkerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelWorkerSurname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelWorkerBirthdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelWorkerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelWorkerTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelWorkerAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelWorkerUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelWorkerPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelWorkerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelWorkerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelWorkerSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelWorkerBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelWorkerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelWorkerTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelWorkerAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelWorkerUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelWorkerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panel.components.PanelLTFS panelWorkerAddress;
    private view.panel.components.PanelLRBS panelWorkerAdmin;
    private view.panel.components.PanelLDPS panelWorkerBirthdate;
    private view.panel.components.PanelLTFBS panelWorkerID;
    private view.panel.components.PanelLTFS panelWorkerName;
    private view.panel.components.PanelLTFS panelWorkerPassword;
    private view.panel.components.PanelLTFS panelWorkerSurname;
    private view.panel.components.PanelLTFS panelWorkerTelephone;
    private view.panel.components.PanelLTFS panelWorkerUsername;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        panelWorkerID.addListener(this);
        panelWorkerID.getTextField().setEnabled(false);
        panelWorkerID.setElementText("Generisi", "Sifra radnika", "");
        panelWorkerAddress.setElementText("Adresa", "");
        panelWorkerBirthdate.setElementText("Datum rodjenja", new Date());
        panelWorkerUsername.setElementText("Korisnicko ime", "");
        panelWorkerPassword.setElementText("Lozinka", "");
        panelWorkerName.setElementText("Ime", "");
        panelWorkerSurname.setElementText("Prezime", "");
        panelWorkerTelephone.setElementText("Telefon", "");
        panelWorkerAdmin.setElementText("Administrator", "Da", "Ne");
    }

    public void clearPanel() {
        panelWorkerID.clearPanel();
        panelWorkerAddress.clearPanel();
        panelWorkerBirthdate.clearPanel();
        panelWorkerUsername.clearPanel();
        panelWorkerPassword.clearPanel();
        panelWorkerName.clearPanel();
        panelWorkerSurname.clearPanel();
        panelWorkerTelephone.clearPanel();
        panelWorkerAdmin.clearPanel();
    }

    @Override
    public Object getValue() {
        Long id = new Long((String) panelWorkerID.getValue());
        String name = (String) panelWorkerName.getValue();
        String surname = (String) panelWorkerSurname.getValue();
        String address = (String) panelWorkerAddress.getValue();
        String telephone = (String) panelWorkerTelephone.getValue();
        String username = (String) panelWorkerUsername.getValue();
        Date birthdate = (Date) panelWorkerBirthdate.getValue();
        String password = (String) panelWorkerPassword.getValue();
//        int admin = (Integer) panelWorkerAdmin.getValue();
        String admin = (String) panelWorkerAdmin.getValue();
        int administrator = 1;
        if (admin.equalsIgnoreCase("Da")) {
            administrator = 1;
        } else {
            if (admin.equalsIgnoreCase("Ne")) {
                administrator = 0;
            }
        }

        Radnik radnik = new Radnik(id, name, surname, username, password, birthdate, address, telephone, administrator);
        return radnik;
    }

    @Override
    public void setValue(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void pressButton(ClickButtonEvent evt) {
        for (GenerateListener generateListener : generateListeners) {
            try {

                DomainObject odo = generateListener.generateOdo(new Radnik());

                panelWorkerID.setValue(odo.getObjectIDValue() + "");
            } catch (Exception ex) {
                Logger.getLogger(PanelAddWorker.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void addListener(GenerateListener toAdd) {
        generateListeners.add(toAdd);
    }
}
