/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.custom;

import controller.CommunicationController;
import domain.Klijent;
import domain.Zivotinja;
import domain.iFrmValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import listeners.MyTableListener;
import listeners.SearchListener;
import view.tableModels.TableModelZivotinja;

/**
 *
 * @author anakl
 */
public class PanelSearchClientsPet extends javax.swing.JPanel implements SearchListener, MyTableListener, iFrmValue {

    private TableModelZivotinja tmz;
    private List<Zivotinja> zivotinje;
    private Zivotinja zivotinja;
    private Klijent klijent;

    /**
     * Creates new form PanelSearchClientsPet
     */
    public PanelSearchClientsPet() {
        initComponents();
        zivotinje = new ArrayList<>();
        zivotinja = new Zivotinja();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearchClientsPet = new view.panel.components.PanelSearch();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchClientsPet, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchClientsPet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panel.components.PanelSearch panelSearchClientsPet;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        tmz = new TableModelZivotinja(zivotinje);
        panelSearchClientsPet.preparePanel(tmz);
        panelSearchClientsPet.addListener(this);
        panelSearchClientsPet.addMyTableListener(this);
    }

    public void clearPanel() {
        zivotinje.clear();
        panelSearchClientsPet.clearPanel(new TableModelZivotinja(zivotinje));
    }

    @Override
    public AbstractTableModel searchOdo(String id) throws Exception {
        try {
            zivotinje = CommunicationController.getInstance().searchClientsPet(Long.valueOf(id));
            JOptionPane.showMessageDialog(this, "Uspesno vraceni ljubimci!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            return new TableModelZivotinja(zivotinje);
        } catch (Exception ex) {
            Logger.getLogger(PanelSearchClient.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }

    @Override
    public void clickedRow(int clickedRow) {
        zivotinja = tmz.getPet(clickedRow);
    }

    @Override
    public Object getValue() {
        return zivotinja;
    }

    @Override
    public void setValue(Object object) {
        this.zivotinja = (Zivotinja) object;
    }

    public void setTableData(Long id) {
        try {
            zivotinje = CommunicationController.getInstance().searchClientsPet(id);
            tmz.azuriraj(zivotinje);
        } catch (Exception ex) {
            Logger.getLogger(PanelSearchClientsPet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
