/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.custom;

import controller.CommunicationController;
import domain.DomainObject;
import domain.PoreskaStopa;
import domain.PredmetProdaje;
import domain.iFrmValue;
import events.ClickButtonEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import listeners.CustomComponentListener;
import listeners.GenerateListener;
import view.panel.components.PanelLTFS;

/**
 *
 * @author anakl
 */
public class PanelAddProduct extends javax.swing.JPanel implements iFrmValue, CustomComponentListener {
    
    private List<GenerateListener> generateListeners = new ArrayList<>();
    private List<PoreskaStopa> pdv;

    /**
     * Creates new form PanelAddProduct
     */
    public PanelAddProduct() {
        initComponents();
        pdv = new ArrayList<>();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelObjectOfSaleID = new view.panel.components.PanelLTFBS();
        panelNumberOfProduct = new view.panel.components.PanelLTFS();
        panelNameOfProduct = new view.panel.components.PanelLTFS();
        panelPriceNoTax = new view.panel.components.PanelLTFS();
        panelPriceWithTax = new view.panel.components.PanelLTFS();
        panelTax = new view.panel.components.PanelLCBS();

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelObjectOfSaleID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNumberOfProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNameOfProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPriceWithTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPriceNoTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelObjectOfSaleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelNumberOfProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelNameOfProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPriceNoTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPriceWithTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panel.components.PanelLTFS panelNameOfProduct;
    private view.panel.components.PanelLTFS panelNumberOfProduct;
    private view.panel.components.PanelLTFBS panelObjectOfSaleID;
    private view.panel.components.PanelLTFS panelPriceNoTax;
    private view.panel.components.PanelLTFS panelPriceWithTax;
    private view.panel.components.PanelLCBS panelTax;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        try {
            panelObjectOfSaleID.addListener(this);
            panelObjectOfSaleID.setEnabled(false);
            panelObjectOfSaleID.setElementText("Generiši", "Šifra predmeta prodaje", "");
            panelNameOfProduct.setElementText("Naziv leka", "");
            panelNumberOfProduct.setElementText("Oznaka leka", "");
            panelPriceNoTax.setElementText("Cena bez PDV-a", "");
            panelPriceWithTax.setElementText("Cena sa PDV-om", "");
            pdv = CommunicationController.getInstance().selectAllTaxes();
            panelTax.getLabel().setText("PDV");
            panelTax.setTaxModel(pdv);
        } catch (Exception ex) {
            Logger.getLogger(PanelAddProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void clearPanel() {
        panelObjectOfSaleID.clearPanel();
        panelNameOfProduct.clearPanel();
        panelNumberOfProduct.clearPanel();
        panelPriceNoTax.clearPanel();
        panelPriceWithTax.clearPanel();
        panelTax.clearPanel();
    }
    
    @Override
    public Object getValue() {
        Long id = new Long((String) panelObjectOfSaleID.getValue());
        String name = (String) panelNameOfProduct.getValue();
        BigDecimal priceNoTax = new BigDecimal((String) panelPriceNoTax.getValue());
        BigDecimal priceWithTax = new BigDecimal((String) panelPriceWithTax.getValue());
        PoreskaStopa pdv = (PoreskaStopa) panelTax.getValue();
        PredmetProdaje pp = new PredmetProdaje(id, name, priceNoTax, priceWithTax, pdv);
        return pp;
    }
    
    @Override
    public void setValue(Object object) {
        System.out.println("");
    }
    
    @Override
    public void pressButton(ClickButtonEvent evt) {
        for (GenerateListener generateListener : generateListeners) {
            try {
                
                DomainObject odo = generateListener.generateOdo(new PredmetProdaje());
                
                panelObjectOfSaleID.setValue(odo.getObjectIDValue() + "");
            } catch (Exception ex) {
                Logger.getLogger(PanelAddClient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public void addListener(GenerateListener toAdd) {
        generateListeners.add(toAdd);
    }
    
    public PanelLTFS getPanelNumberOfProduct() {
        return panelNumberOfProduct;
    }
    
    public void setPanelNumberOfProduct(PanelLTFS panelNumberOfProduct) {
        this.panelNumberOfProduct = panelNumberOfProduct;
    }
    
}
