/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.custom;

import controller.CommunicationController;
import domain.DomainObject;
import domain.Zivotinja;
import domain.iFrmValue;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import listeners.ChooseListener;
import listeners.DeleteObjectListener;
import listeners.MyTableListener;
import listeners.SearchListener;
import listeners.TableDataListener;
import view.tableModels.TableModelZivotinja;

/**
 *
 * @author anakl
 */
public class PanelSearchPet extends javax.swing.JPanel implements TableDataListener, DeleteObjectListener, SearchListener, iFrmValue, MyTableListener {

    private TableModelZivotinja tmz;
    private List<Zivotinja> zivotinje;
    private Zivotinja zivotinja;
    private List<ChooseListener> chooseListeners = new ArrayList<>();

    /**
     * Creates new form PanelSearchPet
     */
    public PanelSearchPet() {
        initComponents();
        zivotinje = new ArrayList<>();
        zivotinja = new Zivotinja();
        fillTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearchPets = new view.panel.components.PanelSearch();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchPets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchPets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panel.components.PanelSearch panelSearchPets;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        tmz = new TableModelZivotinja(zivotinje);
        panelSearchPets.preparePanel(tmz);
        panelSearchPets.addListener(this);
        panelSearchPets.addMyTableListener(this);
        panelSearchPets.setPanelTitle("Pretraži životinje");
    }

    public void clearPanel() {
        zivotinje.clear();
        panelSearchPets.clearPanel(new TableModelZivotinja(zivotinje));
    }

    @Override
    public AbstractTableModel searchOdo(String criteria) throws Exception {
        try {
            zivotinje = CommunicationController.getInstance().searchPetsWithCriteria(criteria);
            JOptionPane.showMessageDialog(this, "Uspesno vraceni ljubimci!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            return new TableModelZivotinja(zivotinje);
        } catch (Exception ex) {
            Logger.getLogger(PanelSearchClient.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }

    @Override
    public void clickedRow(int clickedRow) {
        zivotinja = tmz.getPet(clickedRow);
        for (ChooseListener cl : chooseListeners) {
            try {
                cl.onChooseOdo(zivotinja);
            } catch (Exception ex) {
                Logger.getLogger(PanelSearchPet.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    @Override
    public Object getValue() {
        return zivotinja;
    }

    @Override
    public void setValue(Object object) {
        this.zivotinja = (Zivotinja) object;
    }

    private void fillTableData() {
        try {
            zivotinje = CommunicationController.getInstance().selectAllPets();
        } catch (Exception ex) {
            Logger.getLogger(PanelSearchPet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void addChooseListener(ChooseListener cl) {
        chooseListeners.add(cl);
    }

    @Override
    public void removeObject(DomainObject odo) throws Exception {
        zivotinja = (Zivotinja) getValue();
        CommunicationController.getInstance().deleteObject(zivotinja);
        zivotinje = CommunicationController.getInstance().selectAllPets();
        tmz.azuriraj(zivotinje);
    }

    @Override
    public void updateTable() throws Exception {
        zivotinje = CommunicationController.getInstance().selectAllPets();
        tmz.azuriraj(zivotinje);
    }
}
