/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.custom;

import controller.CommunicationController;
import domain.DomainObject;
import domain.Karton;
import domain.iFrmValue;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import listeners.ChooseListener;
import listeners.DeleteObjectListener;
import listeners.MyTableListener;
import listeners.SearchListener;
import listeners.TableDataListener;
import view.tableModels.TableModelKarton;

/**
 *
 * @author anakl
 */
public class PanelSearchMedicalRecords extends javax.swing.JPanel implements TableDataListener, DeleteObjectListener, SearchListener, MyTableListener, iFrmValue {

    private TableModelKarton tmk;
    private List<Karton> kartoni;
    private Karton karton;
    private List<ChooseListener> chooseListeners = new ArrayList<>();

    /**
     * Creates new form PanelSearchMedicalRecords
     */
    public PanelSearchMedicalRecords() {
        initComponents();
        kartoni = new ArrayList<>();
        karton = new Karton();
        fillTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearchMedicalRecord = new view.panel.components.PanelSearch();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchMedicalRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchMedicalRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panel.components.PanelSearch panelSearchMedicalRecord;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        tmk = new TableModelKarton(kartoni);
        panelSearchMedicalRecord.preparePanel(tmk);
        panelSearchMedicalRecord.addListener(this);
        panelSearchMedicalRecord.addMyTableListener(this);
        panelSearchMedicalRecord.setPanelTitle("Pretraži kartone");
    }

    public void clearPanel() {
        kartoni.clear();
        panelSearchMedicalRecord.clearPanel(new TableModelKarton(kartoni));
    }

    @Override
    public AbstractTableModel searchOdo(String criteria) throws Exception {
        try {
            kartoni = CommunicationController.getInstance().searchMedicalRecordsWithCriteria(criteria);
            JOptionPane.showMessageDialog(this, "Uspesno vraceni kartoni!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            return new TableModelKarton(kartoni);
        } catch (Exception ex) {
            Logger.getLogger(PanelSearchClient.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }

    @Override
    public void clickedRow(int clickedRow) {
        karton = tmk.getMedicalRecord(clickedRow);
        for (ChooseListener chooseListener : chooseListeners) {
            try {
                chooseListener.onChooseOdo(karton);
            } catch (Exception ex) {
                Logger.getLogger(PanelSearchMedicalRecords.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    @Override
    public Object getValue() {
        return karton;
    }

    @Override
    public void setValue(Object object) {
        this.karton = (Karton) object;
    }

    private void fillTableData() {
        try {
            kartoni = CommunicationController.getInstance().selectAllMedicalRecords();
        } catch (Exception ex) {
            Logger.getLogger(PanelSearchClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void addListener(ChooseListener cl) {
        chooseListeners.add(cl);
    }

    @Override
    public void removeObject(DomainObject odo) throws Exception {
        karton = (Karton) odo;
        CommunicationController.getInstance().deleteObject(odo);
        kartoni = CommunicationController.getInstance().selectAllMedicalRecords();
        tmk.azuriraj(kartoni);
    }

    @Override
    public void updateTable() throws Exception {
        kartoni = CommunicationController.getInstance().selectAllMedicalRecords();
        tmk.azuriraj(kartoni);
    }
}
