/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.custom;

import controller.CommunicationController;
import domain.DomainObject;
import domain.Radnik;
import domain.iFrmValue;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import listeners.DeleteObjectListener;
import listeners.MyTableListener;
import listeners.SearchListener;
import listeners.TableDataListener;
import view.tableModels.TableModelRadnik;

/**
 *
 * @author anakl
 */
public class PanelSearchWorker extends javax.swing.JPanel implements TableDataListener, DeleteObjectListener, SearchListener, MyTableListener, iFrmValue {

    private TableModelRadnik tmr;
    private List<Radnik> radnici;
    private Radnik radnik;

    /**
     * Creates new form PanelSearchWorker
     */
    public PanelSearchWorker() {
        initComponents();
        radnici = new ArrayList<>();
        radnik = new Radnik();
        fillTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearchWorker = new view.panel.components.PanelSearch();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchWorker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchWorker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panel.components.PanelSearch panelSearchWorker;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        tmr = new TableModelRadnik(radnici);
        panelSearchWorker.preparePanel(tmr);
        panelSearchWorker.addListener(this);
        panelSearchWorker.addMyTableListener(this);
        panelSearchWorker.setPanelTitle("Pretraži radnike");
    }

    public void clearPanel() {
        radnici.clear();
        panelSearchWorker.clearPanel(new TableModelRadnik(radnici));
    }

    @Override
    public AbstractTableModel searchOdo(String criteria) throws Exception {
        try {
            radnici = CommunicationController.getInstance().searchWorkerWithCriteria(criteria);
            JOptionPane.showMessageDialog(this, "Uspesno vraceni radnici!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            return new TableModelRadnik(radnici);
        } catch (Exception ex) {
            Logger.getLogger(PanelSearchWorker.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }

    @Override
    public void clickedRow(int clickedRow) {
        radnik = tmr.getWorker(clickedRow);
    }

    @Override
    public Object getValue() {
        return radnik;
    }

    @Override
    public void setValue(Object object) {
        this.radnik = (Radnik) object;
    }

    private void fillTableData() {
        try {
            radnici = CommunicationController.getInstance().selectAllWorkers();
        } catch (Exception ex) {
            Logger.getLogger(PanelSearchWorker.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void removeObject(DomainObject odo) throws Exception {

        radnik = (Radnik) getValue();
        CommunicationController.getInstance().deleteObject(radnik);
        radnici = CommunicationController.getInstance().selectAllWorkers();
        tmr.azuriraj(radnici);

    }

    @Override
    public void updateTable() throws Exception {
        radnici = CommunicationController.getInstance().selectAllWorkers();
        tmr.azuriraj(radnici);
    }
}
