/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.custom;

import domain.Radnik;
import domain.iFrmValue;
import java.util.Date;

/**
 *
 * @author anakl
 */
public class PanelEditWorker extends javax.swing.JPanel implements iFrmValue {

    /**
     * Creates new form PanelEditWorker
     */
    public PanelEditWorker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWorkerID = new view.panel.components.PanelLTFS();
        panelWorkerName = new view.panel.components.PanelLTFS();
        panelWorkerSurname = new view.panel.components.PanelLTFS();
        panelWorkerBirthdate = new view.panel.components.PanelLDPS();
        panelWorkerAddress = new view.panel.components.PanelLTFS();
        panelWorkerTelephone = new view.panel.components.PanelLTFS();
        panelWorkerAdmin = new view.panel.components.PanelLRBS();
        panelWorkerUsername = new view.panel.components.PanelLTFS();
        panelWorkerPassword = new view.panel.components.PanelLTFS();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Izmena radnika"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelWorkerBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panelWorkerID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addComponent(panelWorkerName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelWorkerSurname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelWorkerAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelWorkerTelephone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelWorkerAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelWorkerUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelWorkerPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelWorkerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelWorkerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelWorkerSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelWorkerBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelWorkerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelWorkerTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelWorkerAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelWorkerUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelWorkerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panel.components.PanelLTFS panelWorkerAddress;
    private view.panel.components.PanelLRBS panelWorkerAdmin;
    private view.panel.components.PanelLDPS panelWorkerBirthdate;
    private view.panel.components.PanelLTFS panelWorkerID;
    private view.panel.components.PanelLTFS panelWorkerName;
    private view.panel.components.PanelLTFS panelWorkerPassword;
    private view.panel.components.PanelLTFS panelWorkerSurname;
    private view.panel.components.PanelLTFS panelWorkerTelephone;
    private view.panel.components.PanelLTFS panelWorkerUsername;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        panelWorkerID.getTextField().setEnabled(false);
        panelWorkerID.setElementText("Šifra radnika", "");
        panelWorkerAddress.setElementText("Adresa", "");
        panelWorkerBirthdate.setElementText("Datum rođenja", new Date());
        panelWorkerUsername.setElementText("Korisničko ime", "");
        panelWorkerPassword.setElementText("Lozinka", "");
        panelWorkerName.setElementText("Ime", "");
        panelWorkerSurname.setElementText("Prezime", "");
        panelWorkerTelephone.setElementText("Telefon", "");
        panelWorkerAdmin.setElementText("Administrator", "Da", "Ne");
    }

    public void clearPanel() {
        panelWorkerID.clearPanel();
        panelWorkerAddress.clearPanel();
        panelWorkerBirthdate.clearPanel();
        panelWorkerUsername.clearPanel();
        panelWorkerPassword.clearPanel();
        panelWorkerName.clearPanel();
        panelWorkerSurname.clearPanel();
        panelWorkerTelephone.clearPanel();
        panelWorkerAdmin.clearPanel();
    }

    @Override
    public Object getValue() {
        Long id = new Long((String) panelWorkerID.getValue());
        String name = (String) panelWorkerName.getValue();
        String surname = (String) panelWorkerSurname.getValue();
        String address = (String) panelWorkerAddress.getValue();
        String telephone = (String) panelWorkerTelephone.getValue();
        String username = (String) panelWorkerUsername.getValue();
        Date birthdate = (Date) panelWorkerBirthdate.getValue();
        String password = (String) panelWorkerPassword.getValue();
//        int admin = (Integer) panelWorkerAdmin.getValue();
        boolean admin = (boolean) panelWorkerAdmin.getValue();

        Radnik radnik = new Radnik(id, name, surname, username, password, birthdate, address, telephone, admin);
        return radnik;
    }

    @Override
    public void setValue(Object object) {
        Radnik radnik = (Radnik) object;
        panelWorkerID.setValue(radnik.getRadnikID() + "");
        panelWorkerAddress.setValue(radnik.getAdresa());
        panelWorkerAdmin.setValue(radnik.isAdministrator());
        panelWorkerName.setValue(radnik.getIme());
        panelWorkerSurname.setValue(radnik.getPrezime());
        panelWorkerUsername.setValue(radnik.getKorisnikoIme());
        panelWorkerPassword.setValue(radnik.getLozinka());
        panelWorkerBirthdate.setValue(radnik.getDatumRodjenja());
        panelWorkerTelephone.setValue(radnik.getTelefon());

    }
}
