/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.custom;

import controller.ClientController;
import controller.CommunicationController;
import domain.DomainObject;
import domain.Karton;
import domain.PoreskaStopa;
import domain.Racun;
import domain.Radnik;
import domain.iFrmValue;
import events.ClickButtonEvent;
import java.awt.Frame;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import listeners.CustomComponentListener;
import listeners.GenerateListener;
import listeners.MedicalRecordChooseListener;
import view.dialogs.DialogChooseMedicalRecord;
import view.panel.components.PanelLTFBS;
import view.panel.components.PanelLTFS;

/**
 *
 * @author anakl
 */
public class PanelAddBill extends javax.swing.JPanel implements iFrmValue, CustomComponentListener, MedicalRecordChooseListener {

    private List<GenerateListener> generateListeners = new ArrayList<>();
    private Radnik radnik;
    private Karton karton;
    private List<PoreskaStopa> pdv;
    private DialogChooseMedicalRecord dialogChooseMedicalRecord;

    /**
     * Creates new form PanelAddBill
     */
    public PanelAddBill() {
        initComponents();
        pdv = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBillID = new view.panel.components.PanelLTFBS();
        panelBillMedicalRecordID = new view.panel.components.PanelLTFBS();
        panelBillWorker = new view.panel.components.PanelLTFS();
        panelBillDateCreated = new view.panel.components.PanelLDPS();
        panelBillTotalPriceNoTax = new view.panel.components.PanelLTFS();
        panelBillTotalPriceTax = new view.panel.components.PanelLTFS();
        panelBillTax = new view.panel.components.PanelLCBS();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(420, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBillTotalPriceNoTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBillWorker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBillID, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panelBillMedicalRecordID, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panelBillDateCreated, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBillTotalPriceTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBillTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBillID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBillMedicalRecordID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBillWorker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBillDateCreated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBillTotalPriceNoTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBillTotalPriceTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBillTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panel.components.PanelLDPS panelBillDateCreated;
    private view.panel.components.PanelLTFBS panelBillID;
    private view.panel.components.PanelLTFBS panelBillMedicalRecordID;
    private view.panel.components.PanelLCBS panelBillTax;
    private view.panel.components.PanelLTFS panelBillTotalPriceNoTax;
    private view.panel.components.PanelLTFS panelBillTotalPriceTax;
    private view.panel.components.PanelLTFS panelBillWorker;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        try {
            panelBillID.addListener(this);
            panelBillMedicalRecordID.addListener(this);
            panelBillID.getTextField().setEnabled(false);
            panelBillMedicalRecordID.setEnabled(false);
            panelBillWorker.setEnabled(false);
            panelBillID.setElementText("Generiši", "Šifra računa", "");
            panelBillMedicalRecordID.setElementText("Izaberi karton", "Šifra kartona", "");
            panelBillDateCreated.setElementText("Datum kreiranja", new Date());
            panelBillWorker.setElementText("Radnik", ClientController.getInstance().getRadnik().toString());
            panelBillTotalPriceTax.setElementText("Ukupna cena sa PDV-om", "0");
            panelBillTotalPriceNoTax.setElementText("Ukupna cena bez PDV-a", "0");
            pdv = CommunicationController.getInstance().selectAllTaxes();
            panelBillTax.getLabel().setText("PDV");
            panelBillTax.setTaxModel(pdv);
        } catch (Exception ex) {
            Logger.getLogger(PanelAddBill.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void clearPanel() {
        panelBillID.clearPanel();
        panelBillMedicalRecordID.clearPanel();
        panelBillDateCreated.clearPanel();
        panelBillWorker.clearPanel();
        panelBillTotalPriceTax.clearPanel();
        panelBillTotalPriceNoTax.clearPanel();
    }

    @Override
    public Object getValue() {
        Long id = new Long((String) panelBillID.getValue());
        Date datum = (Date) panelBillDateCreated.getValue();
        BigDecimal ukupnaCenaSaPDV = new BigDecimal((String) panelBillTotalPriceTax.getValue());
        BigDecimal ukupnaCenaBezPDV = new BigDecimal((String) panelBillTotalPriceNoTax.getValue());
        BigDecimal pdv = new BigDecimal(((PoreskaStopa) panelBillTax.getValue()).getVrednost() + "");
        radnik = controller.ClientController.getInstance().getRadnik();
        Racun racun = new Racun(id, ukupnaCenaSaPDV, ukupnaCenaBezPDV, pdv, false, false, radnik, karton, datum);
        return racun;
    }

    @Override
    public void setValue(Object object) {
        Racun racun = (Racun) object;
        panelBillID.setValue(racun.getRacunID() + "");
        panelBillMedicalRecordID.setValue(racun.getKarton().getKartonID() + "");
        panelBillWorker.setValue(racun.getRadnik().toString());
        panelBillDateCreated.setValue(racun.getDatumKreiranja());
        panelBillTotalPriceNoTax.setValue(racun.getUkupnaCenaBezPoreza() + "");
        panelBillTotalPriceTax.setValue(racun.getUkupnaCenaSaPorezom() + "");
        panelBillTax.setValue(racun.getPorez() + "");
    }

    @Override
    public void pressButton(ClickButtonEvent evt) {
        if (evt.getSource() == panelBillID) {
            for (GenerateListener generateListener : generateListeners) {
                try {
                    DomainObject odo = generateListener.generateOdo(new Racun());
                    panelBillID.setValue(odo.getObjectIDValue() + "");
                } catch (Exception ex) {
                    Logger.getLogger(PanelAddClient.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if (evt.getSource() == panelBillMedicalRecordID) {
            dialogChooseMedicalRecord = new DialogChooseMedicalRecord((Frame) SwingUtilities.getWindowAncestor(SwingUtilities.getWindowAncestor(this)), true);
            dialogChooseMedicalRecord.addListener(this);
            dialogChooseMedicalRecord.setVisible(true);
        }
    }

    public void addListener(GenerateListener toAdd) {
        generateListeners.add(toAdd);
    }

    @Override
    public void chooseMedicalRecord(Karton karton) {
        this.karton = karton;
        panelBillMedicalRecordID.setValue(karton.getKartonID() + "");
    }

}
