/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.custom;

import domain.StavkaRacuna;
import domain.iFrmValue;
import java.util.ArrayList;
import java.util.List;
import listeners.MyTableListener;
import view.tableModels.TableModelStavkaRacuna;

/**
 *
 * @author anakl
 */
public class PanelSearchItemOfBill extends javax.swing.JPanel implements MyTableListener, iFrmValue {

    private TableModelStavkaRacuna tmsr;
    private List<StavkaRacuna> stavkeRacuna;
    private StavkaRacuna stavka;

    /**
     * Creates new form PanelSearchItemOfSale
     */
    public PanelSearchItemOfBill() {
        initComponents();
        stavkeRacuna = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearchItemOfBill = new view.panel.components.PanelSearch();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchItemOfBill, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchItemOfBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panel.components.PanelSearch panelSearchItemOfBill;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        tmsr = new TableModelStavkaRacuna(stavkeRacuna);
        panelSearchItemOfBill.preparePanel(tmsr);
//        panelSearchItemOfBill.addListener(this);
//        panelSearchItemOfBill.addMyTableListener(this);
    }

    public void clearPanel() {
        stavkeRacuna.clear();
        panelSearchItemOfBill.clearPanel(new TableModelStavkaRacuna(stavkeRacuna));
    }

    @Override
    public void clickedRow(int clickedRow) {
        stavka = tmsr.getItemOfBill(clickedRow);
    }

    @Override
    public Object getValue() {
        return stavka;
    }

    @Override
    public void setValue(Object object) {
        this.stavka = (StavkaRacuna) object;
    }

}
