/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.custom;

import domain.Karton;
import domain.Radnik;
import domain.Zivotinja;
import domain.iFrmValue;
import java.util.Date;

/**
 *
 * @author anakl
 */
public class PanelEditMedicalRecord extends javax.swing.JPanel implements iFrmValue {

    private Zivotinja zivotinja;
    private Radnik radnik;

    /**
     * Creates new form PanelEditMedicalRecord
     */
    public PanelEditMedicalRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMedicalRecordID = new view.panel.components.PanelLTFS();
        panelMedicalRecordDate = new view.panel.components.PanelLDPS();
        panelMedicalRecordNote = new view.panel.components.PanelLTAS();
        panelMedicalRecordWorker = new view.panel.components.PanelLTFS();
        panelMedicalRecordAnimal = new view.panel.components.PanelLTFS();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Izmena kartona"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMedicalRecordAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMedicalRecordID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMedicalRecordDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMedicalRecordNote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMedicalRecordWorker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMedicalRecordID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMedicalRecordDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMedicalRecordNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMedicalRecordWorker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMedicalRecordAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panel.components.PanelLTFS panelMedicalRecordAnimal;
    private view.panel.components.PanelLDPS panelMedicalRecordDate;
    private view.panel.components.PanelLTFS panelMedicalRecordID;
    private view.panel.components.PanelLTAS panelMedicalRecordNote;
    private view.panel.components.PanelLTFS panelMedicalRecordWorker;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {

        panelMedicalRecordID.getTextField().setEnabled(false);
        panelMedicalRecordID.setElementText("Šifra kartona", "");
        panelMedicalRecordNote.setElementText("Napomena", "");
        panelMedicalRecordDate.setElementText("Datum kreiranja", new Date());
        panelMedicalRecordWorker.setElementText("Radnik", "");
        panelMedicalRecordAnimal.setElementText("Životinja", "");

    }

    public void clearPanel() {
        panelMedicalRecordID.clearPanel();
        panelMedicalRecordAnimal.clearPanel();
        panelMedicalRecordNote.clearPanel();
        panelMedicalRecordWorker.clearPanel();
        panelMedicalRecordDate.clearPanel();
    }

    @Override
    public Object getValue() {
        Long id = new Long((String) panelMedicalRecordID.getValue());
        String note = (String) panelMedicalRecordNote.getValue();
        Date dateCreated = (Date) panelMedicalRecordDate.getValue();

        Karton karton = new Karton(id, dateCreated, note, radnik, zivotinja);
        return karton;
    }

    @Override
    public void setValue(Object object) {
        Karton karton = (Karton) object;
        panelMedicalRecordID.setValue(karton.getKartonID() + "");
        panelMedicalRecordAnimal.setValue(karton.getZivotinja().getIme() + "");
        panelMedicalRecordNote.setValue(karton.getNapomena());
        panelMedicalRecordDate.setValue(karton.getDatumKreiranja());
        panelMedicalRecordWorker.setValue(karton.getRadnik().getIme() + "");
    }
}
