/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.custom;

import domain.DomainObject;
import domain.Karton;
import domain.Radnik;
import domain.Zivotinja;
import domain.iFrmValue;
import events.ClickButtonEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import listeners.CustomComponentListener;
import listeners.GenerateListener;
import view.panel.components.PanelLTFS;

/**
 *
 * @author anakl
 */
public class PanelAddMedicalRecord extends javax.swing.JPanel implements iFrmValue, CustomComponentListener {
    
    private List<GenerateListener> generateListeners = new ArrayList<>();
    private Zivotinja zivotinja;
    private Radnik radnik;

    /**
     * Creates new form PanelAddMedicalRecord
     */
    public PanelAddMedicalRecord(Zivotinja zivotinja, Radnik radnik) {
        initComponents();
        this.zivotinja = zivotinja;
        this.radnik = radnik;
    }
    
    public PanelAddMedicalRecord() {
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMedicalRecordID = new view.panel.components.PanelLTFBS();
        panelMedicalRecordDateCreated = new view.panel.components.PanelLDPS();
        panelMedicalRecordNote = new view.panel.components.PanelLTAS();
        panelMedicalRecordWorker = new view.panel.components.PanelLTFS();
        panelMedicalRecordAnimalID = new view.panel.components.PanelLTFS();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Add medical record"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMedicalRecordID, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addComponent(panelMedicalRecordDateCreated, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMedicalRecordNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMedicalRecordWorker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMedicalRecordAnimalID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMedicalRecordID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMedicalRecordDateCreated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMedicalRecordNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMedicalRecordWorker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMedicalRecordAnimalID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panel.components.PanelLTFS panelMedicalRecordAnimalID;
    private view.panel.components.PanelLDPS panelMedicalRecordDateCreated;
    private view.panel.components.PanelLTFBS panelMedicalRecordID;
    private view.panel.components.PanelLTAS panelMedicalRecordNote;
    private view.panel.components.PanelLTFS panelMedicalRecordWorker;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        panelMedicalRecordID.addListener(this);
        panelMedicalRecordID.getTextField().setEnabled(false);
        panelMedicalRecordID.setElementText("Generisi", "Sifra kartona", "");
        panelMedicalRecordAnimalID.setElementText("Sifra zivotinje", "");
        panelMedicalRecordAnimalID.setEnabled(false);
        panelMedicalRecordNote.setElementText("Napomena", "");
        panelMedicalRecordWorker.setElementText("Sifra radnika", "");
        panelMedicalRecordDateCreated.setElementText("Datum kreiranja", new Date());
    }
    
    public void clearPanel() {
        panelMedicalRecordID.clearPanel();
        panelMedicalRecordAnimalID.clearPanel();
        panelMedicalRecordNote.clearPanel();
        panelMedicalRecordWorker.clearPanel();
        panelMedicalRecordDateCreated.clearPanel();
    }
    
    @Override
    public Object getValue() {
        Long id = new Long((String) panelMedicalRecordID.getValue());
        String note = (String) panelMedicalRecordNote.getValue();
        Date dateCreated = (Date) panelMedicalRecordDateCreated.getValue();
        Karton karton = new Karton(id, dateCreated, note, radnik, zivotinja);
        return karton;
    }
    
    @Override
    public void setValue(Object object) {
        Karton karton = (Karton) object;
        panelMedicalRecordID.setValue(karton.getKartonID() + "");
        panelMedicalRecordAnimalID.setValue(karton.getZivotinja().getZivotinjaID() + "");
        panelMedicalRecordNote.setValue(karton.getNapomena());
        panelMedicalRecordDateCreated.setValue(karton.getDatumKreiranja());
        panelMedicalRecordWorker.setValue(karton.getRadnik().getRadnikID() + "");
    }
    
    public void addListener(GenerateListener toAdd) {
        generateListeners.add(toAdd);
    }
    
    @Override
    public void pressButton(ClickButtonEvent evt) {
        for (GenerateListener generateListener : generateListeners) {
            try {
                
                DomainObject odo = generateListener.generateOdo(new Karton());
                
                panelMedicalRecordID.setValue(odo.getObjectIDValue() + "");
            } catch (Exception ex) {
                Logger.getLogger(PanelAddClient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public PanelLTFS getPanelMedicalRecordAnimalID() {
        return panelMedicalRecordAnimalID;
    }
    
    public void setPanelMedicalRecordAnimalID(PanelLTFS panelMedicalRecordAnimalID) {
        this.panelMedicalRecordAnimalID = panelMedicalRecordAnimalID;
    }
    
    public PanelLTFS getPanelMedicalRecordWorker() {
        return panelMedicalRecordWorker;
    }
    
    public void setPanelMedicalRecordWorker(PanelLTFS panelMedicalRecordWorker) {
        this.panelMedicalRecordWorker = panelMedicalRecordWorker;
    }
    
    private void prepareView() {
        panelMedicalRecordAnimalID.setEnabled(false);
        panelMedicalRecordWorker.setEnabled(false);
    }
    
    public void setDisabledFields() {
        panelMedicalRecordWorker.setEnabled(false);
        panelMedicalRecordAnimalID.setEnabled(false);
    }
    
}
