/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.custom;

import controller.CommunicationController;
import domain.DomainObject;
import domain.PredmetProdaje;
import domain.iFrmValue;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import listeners.ChooseListener;
import listeners.DeleteObjectListener;
import listeners.ItemOfBillChooseListener;
import listeners.MyTableListener;
import listeners.SearchListener;
import view.tableModels.TableModelPredmetProdaje;

/**
 *
 * @author anakl
 */
public class PanelSearchObjectOfSale extends javax.swing.JPanel implements DeleteObjectListener, SearchListener, MyTableListener, iFrmValue {

    private TableModelPredmetProdaje tmpp;
    private List<PredmetProdaje> predmetiProdaje;
    private PredmetProdaje predmet;
    private List<ChooseListener> chooseListeners = new ArrayList<>();

    /**
     * Creates new form PanelObjectOfSale
     */
    public PanelSearchObjectOfSale() {
        initComponents();
        fillTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearchObjectOfSale = new view.panel.components.PanelSearch();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchObjectOfSale, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSearchObjectOfSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panel.components.PanelSearch panelSearchObjectOfSale;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        tmpp = new TableModelPredmetProdaje(predmetiProdaje);
        panelSearchObjectOfSale.preparePanel(tmpp);
        panelSearchObjectOfSale.addListener(this);
        panelSearchObjectOfSale.addMyTableListener(this);
    }

    public void clearPanel() {
        predmetiProdaje.clear();
        panelSearchObjectOfSale.clearPanel(new TableModelPredmetProdaje(predmetiProdaje));
    }

    @Override
    public AbstractTableModel searchOdo(String criteria) throws Exception {
        try {
            predmetiProdaje = CommunicationController.getInstance().selectAllObjectOfSale();
            JOptionPane.showMessageDialog(this, "Uspesno vraceni predmeti prodaje!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            return new TableModelPredmetProdaje(predmetiProdaje);
        } catch (Exception ex) {
            Logger.getLogger(PanelSearchObjectOfSale.class.getName()).log(Level.SEVERE, null, ex);
            throw ex;
        }
    }

    @Override
    public void clickedRow(int clickedRow) {
        predmet = tmpp.getObjectOfSale(clickedRow);
        for (ChooseListener cl : chooseListeners) {
            try {
                cl.onChooseOdo(predmet);
            } catch (Exception ex) {
                Logger.getLogger(PanelSearchPet.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    @Override
    public Object getValue() {
        return predmet;
    }

    @Override
    public void setValue(Object object) {
        this.predmet = (PredmetProdaje) object;
    }

    private void fillTableData() {
        try {
            predmetiProdaje = CommunicationController.getInstance().selectAllObjectOfSale();
        } catch (Exception ex) {
            Logger.getLogger(PanelSearchObjectOfSale.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void removeObject(DomainObject odo) throws Exception {
        predmet = (PredmetProdaje) getValue();
        CommunicationController.getInstance().deleteObject(predmet);
        predmetiProdaje = CommunicationController.getInstance().selectAllObjectOfSale();
        tmpp.azuriraj(predmetiProdaje);
    }

    public void addChooseListener(ChooseListener cl) {
        chooseListeners.add(cl);
    }

//    public void addItemListener(ItemOfBillChooseListener item) {
//        items.add(item);
//    }
//    
//    public void onChooseItem(PredmetProdaje predmet){
//        for (ItemOfBillChooseListener item : items) {
//            item.onChooseItemOfBill(predmet);
//        }
//    }
}
