/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.custom;

import controller.CommunicationController;
import domain.DomainObject;
import domain.Klijent;
import domain.iFrmValue;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import listeners.DeleteObjectListener;
import listeners.MyTableListener;
import listeners.SearchListener;
import listeners.TableDataListener;
import view.tableModels.TableModelKlijent;

/**
 *
 * @author anakl
 */
public class PanelSearchClient extends javax.swing.JPanel implements SearchListener, MyTableListener, iFrmValue, DeleteObjectListener, TableDataListener {

    private TableModelKlijent tmk;
    private List<Klijent> klijenti;
    private Klijent klijent;

    /**
     * Creates new form PanelSearchClient
     */
    public PanelSearchClient() {
        initComponents();
        klijenti = new ArrayList<>();
        klijent = new Klijent();
        fillTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearchClient = new view.panel.components.PanelSearch();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panel.components.PanelSearch panelSearchClient;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        tmk = new TableModelKlijent(klijenti);
        panelSearchClient.preparePanel(tmk);
        panelSearchClient.addListener(this);
        panelSearchClient.addMyTableListener(this);
        panelSearchClient.setPanelTitle("Pretraži klijente");

    }

    public void clearPanel() {
        klijenti.clear();
        panelSearchClient.clearPanel(new TableModelKlijent(klijenti));
    }

    @Override
    public AbstractTableModel searchOdo(String criteria) throws Exception {
        try {
            klijenti = CommunicationController.getInstance().searchClientsWithCriteria(criteria);
            JOptionPane.showMessageDialog(this, "Sistem je izvršio pretragu klijenata po zadatoj vrednosti.", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            return new TableModelKlijent(klijenti);
        } catch (Exception ex) {
            Logger.getLogger(PanelSearchClient.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe klijenta po zadatoj vrednosti.", "Greška", JOptionPane.ERROR_MESSAGE);
            throw ex;
        }
    }

    private void fillTableData() {
        try {
            klijenti = CommunicationController.getInstance().selectAllClients();
        } catch (Exception ex) {
            Logger.getLogger(PanelSearchClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void clickedRow(int clickedRow) {
        klijent = tmk.getClient(clickedRow);
    }

    @Override
    public Object getValue() {
        return klijent;
    }

    @Override
    public void setValue(Object object) {
        this.klijent = (Klijent) object;
    }

    @Override
    public void removeObject(DomainObject odo) throws Exception {

        klijent = (Klijent) getValue();
        CommunicationController.getInstance().deleteObject(klijent);
        klijenti = CommunicationController.getInstance().selectAllClients();
        tmk.azuriraj(klijenti);

    }

    public void updateTable() throws Exception {
        klijenti = CommunicationController.getInstance().selectAllClients();
        tmk.azuriraj(klijenti);
    }
}
