/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel.custom;

import domain.BojaZivotinja;
import domain.Klijent;
import domain.RasaMacke;
import domain.RasaPsa;
import domain.VrstaZivotinje;
import domain.Zivotinja;
import domain.iFrmValue;
import events.SelectionChangeEvent;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import listeners.ComboBoxListener;

/**
 *
 * @author anakl
 */
public class PanelEditAnimal extends javax.swing.JPanel implements iFrmValue, ComboBoxListener {

    private Klijent klijent;

    /**
     * Creates new form PanelEditAnimal
     */
    public PanelEditAnimal(Klijent klijent) {
        initComponents();
        this.klijent = klijent;

    }

    public PanelEditAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAnimalID = new view.panel.components.PanelLTFS();
        panelAnimalName = new view.panel.components.PanelLTFS();
        panelAnimalBreed = new view.panel.components.PanelLCBS();
        panelAnimalColor = new view.panel.components.PanelLCBS();
        panelAnimalGender = new view.panel.components.PanelLRBS();
        panelAnimalDate = new view.panel.components.PanelLDPS();
        panelAnimalClientID = new view.panel.components.PanelLTFS();
        panelAnimalType = new view.panel.components.PanelLCBS();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Izmena životinje"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAnimalID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAnimalName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAnimalBreed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAnimalColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAnimalGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAnimalDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAnimalClientID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAnimalType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAnimalID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAnimalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAnimalType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAnimalBreed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAnimalColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAnimalGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAnimalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAnimalClientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.panel.components.PanelLCBS panelAnimalBreed;
    private view.panel.components.PanelLTFS panelAnimalClientID;
    private view.panel.components.PanelLCBS panelAnimalColor;
    private view.panel.components.PanelLDPS panelAnimalDate;
    private view.panel.components.PanelLRBS panelAnimalGender;
    private view.panel.components.PanelLTFS panelAnimalID;
    private view.panel.components.PanelLTFS panelAnimalName;
    private view.panel.components.PanelLCBS panelAnimalType;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        panelAnimalType.addListener(this);
        panelAnimalID.getTextField().setEnabled(false);
        panelAnimalID.setElementText("Šifra životinje", "");
        panelAnimalName.setElementText("Ime", "");
        panelAnimalDate.setElementText("Datum rođenja", new Date());
        panelAnimalBreed.setElementText("Rasa", new DefaultComboBoxModel<>(RasaMacke.values()));
        panelAnimalGender.setElementText("Pol", "Ženski", "Muški");
        panelAnimalType.setElementText("Vrsta", new DefaultComboBoxModel<>(VrstaZivotinje.values()));
        panelAnimalColor.setElementText("Boja", new DefaultComboBoxModel<>(BojaZivotinja.values()));
        panelAnimalClientID.setElementText("Šifra klijenta", "");
        panelAnimalClientID.getTextField().setEnabled(false);
    }

    public void clearPanel() {
        panelAnimalID.clearPanel();
        panelAnimalName.clearPanel();
        panelAnimalDate.clearPanel();
        panelAnimalBreed.clearPanel();
        panelAnimalGender.clearPanel();
        panelAnimalType.clearPanel();
        panelAnimalColor.clearPanel();
        panelAnimalClientID.clearPanel();
    }

    @Override
    public Object getValue() {
        Long id = new Long((String) panelAnimalID.getValue());
        String name = (String) panelAnimalName.getValue();
        String breed = String.valueOf(panelAnimalBreed.getValue());
        String type = String.valueOf(panelAnimalType.getValue());
        String color = String.valueOf(panelAnimalColor.getValue());
        String gender = ((boolean) panelAnimalGender.getValue() ? "Muški" : "Ženski");
        Date birthdate = (Date) panelAnimalDate.getValue();
        Zivotinja zivotinja = new Zivotinja(id, name, breed, type, color, gender, birthdate, klijent);
        return zivotinja;
    }

    @Override
    public void setValue(Object object) {
        Zivotinja zivotinja = (Zivotinja) object;
        panelAnimalBreed.setValue(zivotinja.getZivotinjaID() + "");
        panelAnimalClientID.setValue(zivotinja.getKlijent().getKlijentID() + "");
        panelAnimalType.setValue(zivotinja.getVrsta());
        panelAnimalGender.setValue(zivotinja.getPol().equals("Muški"));
        panelAnimalName.setValue(zivotinja.getIme());
        panelAnimalDate.setValue(zivotinja.getDatumRodjenja());
        panelAnimalColor.setValue(zivotinja.getBoja());
        panelAnimalID.setValue(zivotinja.getZivotinjaID() + "");
    }

    @Override
    public void onChangeSelected(SelectionChangeEvent evt, Object object) {
        VrstaZivotinje vz = (VrstaZivotinje) object;
        if (vz == VrstaZivotinje.Macka) {
            panelAnimalBreed.setElementText("Rasa", new DefaultComboBoxModel<>(RasaMacke.values()));
        } else {
            panelAnimalBreed.setElementText("Rasa", new DefaultComboBoxModel<>(RasaPsa.values()));
        }
    }

}
