/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.main;

import domain.DomainObject;
import domain.Karton;
import domain.Klijent;
import domain.Radnik;
import java.awt.Color;
import java.awt.Frame;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import view.dialogs.DialogAddBill;
import view.dialogs.DialogAddClient;
import view.dialogs.DialogAddMedicalRecord;
import view.dialogs.DialogAddStorage;
import view.dialogs.DialogAddWorker;
import view.dialogs.DialogEditClient;
import view.dialogs.DialogEditMedicalRecord;
import view.dialogs.DialogEditWorker;

/**
 *
 * @author anakl
 */
public class FrmMainWork extends javax.swing.JFrame {

    private Radnik radnik;
    private Klijent klijent;
    private JPanel activePanel;

    /**
     * Creates new form FrmMainWork
     */
    public FrmMainWork(Radnik radnik) {
        initComponents();
        setLocationRelativeTo(null);
        this.radnik = radnik;

        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        lblWorkerLogo = new javax.swing.JLabel();
        lblWorkerName = new javax.swing.JLabel();
        sidePanelExit = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        lblExitLogoText = new javax.swing.JLabel();
        lblExitLogo = new javax.swing.JLabel();
        sidePanelClients = new javax.swing.JPanel();
        lblClientsLogo = new javax.swing.JLabel();
        lblClientsLogoText = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        sidePanelMedicalReports = new javax.swing.JPanel();
        lblMedicalReportsLogo = new javax.swing.JLabel();
        lblMedicalReportsLogoText = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        sidePanelBills = new javax.swing.JPanel();
        lblBillsLogo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblBillsLogoText = new javax.swing.JLabel();
        sidePanelStorage = new javax.swing.JPanel();
        lblStorageLogo1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lblStorageLogoText = new javax.swing.JLabel();
        sidePanelWorkers = new javax.swing.JPanel();
        lblWorkersLogo = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        lblWorkersLogoText = new javax.swing.JLabel();
        horizontalPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        layeredPane = new javax.swing.JLayeredPane();
        panelClients = new javax.swing.JPanel();
        panelSearchClient = new view.panel.custom.PanelSearchClient();
        panelMedicalRecords = new javax.swing.JPanel();
        panelSearchMedicalRecords = new view.panel.custom.PanelSearchMedicalRecords();
        panelBills = new javax.swing.JPanel();
        panelSearchBill = new view.panel.custom.PanelSearchBill();
        panelStorage = new javax.swing.JPanel();
        panelSearchObjectOfSale = new view.panel.custom.PanelSearchObjectOfSale();
        panelWorkers = new javax.swing.JPanel();
        panelSearchWorker = new view.panel.custom.PanelSearchWorker();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));
        panelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(26, 36, 87));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWorkerLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user20px.png"))); // NOI18N
        sidePanel.add(lblWorkerLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        lblWorkerName.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblWorkerName.setForeground(new java.awt.Color(255, 255, 255));
        lblWorkerName.setText("label:");
        sidePanel.add(lblWorkerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 130, -1));

        sidePanelExit.setBackground(new java.awt.Color(79, 88, 133));
        sidePanelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidePanelElementsMousePressed(evt);
            }
        });

        lblExitLogoText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblExitLogoText.setForeground(new java.awt.Color(255, 255, 255));
        lblExitLogoText.setText("label");

        lblExitLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit30px.png"))); // NOI18N

        javax.swing.GroupLayout sidePanelExitLayout = new javax.swing.GroupLayout(sidePanelExit);
        sidePanelExit.setLayout(sidePanelExitLayout);
        sidePanelExitLayout.setHorizontalGroup(
            sidePanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExitLogo)
                .addGap(18, 18, 18)
                .addGroup(sidePanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelExitLayout.createSequentialGroup()
                        .addComponent(lblExitLogoText)
                        .addGap(90, 90, 90))
                    .addComponent(jSeparator4))
                .addContainerGap())
        );
        sidePanelExitLayout.setVerticalGroup(
            sidePanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelExitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblExitLogoText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(sidePanelExitLayout.createSequentialGroup()
                .addComponent(lblExitLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidePanel.add(sidePanelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 180, 40));

        sidePanelClients.setBackground(new java.awt.Color(85, 65, 118));
        sidePanelClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidePanelElementsMousePressed(evt);
            }
        });

        lblClientsLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clients30px.png"))); // NOI18N

        lblClientsLogoText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblClientsLogoText.setForeground(new java.awt.Color(255, 255, 255));
        lblClientsLogoText.setText("label");

        javax.swing.GroupLayout sidePanelClientsLayout = new javax.swing.GroupLayout(sidePanelClients);
        sidePanelClients.setLayout(sidePanelClientsLayout);
        sidePanelClientsLayout.setHorizontalGroup(
            sidePanelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelClientsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClientsLogo)
                .addGap(18, 18, 18)
                .addGroup(sidePanelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelClientsLayout.createSequentialGroup()
                        .addComponent(lblClientsLogoText)
                        .addGap(28, 89, Short.MAX_VALUE))
                    .addComponent(jSeparator1)))
        );
        sidePanelClientsLayout.setVerticalGroup(
            sidePanelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelClientsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(sidePanelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClientsLogo)
                    .addGroup(sidePanelClientsLayout.createSequentialGroup()
                        .addComponent(lblClientsLogoText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        sidePanel.add(sidePanelClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 180, 40));

        sidePanelMedicalReports.setBackground(new java.awt.Color(79, 88, 133));
        sidePanelMedicalReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidePanelElementsMousePressed(evt);
            }
        });

        lblMedicalReportsLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/medicalhistory30px.png"))); // NOI18N

        lblMedicalReportsLogoText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMedicalReportsLogoText.setForeground(new java.awt.Color(255, 255, 255));
        lblMedicalReportsLogoText.setText("label");

        javax.swing.GroupLayout sidePanelMedicalReportsLayout = new javax.swing.GroupLayout(sidePanelMedicalReports);
        sidePanelMedicalReports.setLayout(sidePanelMedicalReportsLayout);
        sidePanelMedicalReportsLayout.setHorizontalGroup(
            sidePanelMedicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelMedicalReportsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMedicalReportsLogo)
                .addGap(18, 18, 18)
                .addGroup(sidePanelMedicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelMedicalReportsLayout.createSequentialGroup()
                        .addComponent(lblMedicalReportsLogoText)
                        .addContainerGap(89, Short.MAX_VALUE))
                    .addComponent(jSeparator2)))
        );
        sidePanelMedicalReportsLayout.setVerticalGroup(
            sidePanelMedicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelMedicalReportsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sidePanelMedicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedicalReportsLogo)
                    .addGroup(sidePanelMedicalReportsLayout.createSequentialGroup()
                        .addComponent(lblMedicalReportsLogoText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        sidePanel.add(sidePanelMedicalReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, 40));

        sidePanelBills.setBackground(new java.awt.Color(79, 88, 133));
        sidePanelBills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidePanelElementsMousePressed(evt);
            }
        });

        lblBillsLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bills30px.png"))); // NOI18N

        lblBillsLogoText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBillsLogoText.setForeground(new java.awt.Color(255, 255, 255));
        lblBillsLogoText.setText("label");

        javax.swing.GroupLayout sidePanelBillsLayout = new javax.swing.GroupLayout(sidePanelBills);
        sidePanelBills.setLayout(sidePanelBillsLayout);
        sidePanelBillsLayout.setHorizontalGroup(
            sidePanelBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelBillsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBillsLogo)
                .addGap(18, 18, 18)
                .addGroup(sidePanelBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelBillsLayout.createSequentialGroup()
                        .addComponent(lblBillsLogoText)
                        .addGap(90, 90, 90))
                    .addComponent(jSeparator3))
                .addContainerGap())
        );
        sidePanelBillsLayout.setVerticalGroup(
            sidePanelBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelBillsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sidePanelBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBillsLogo)
                    .addGroup(sidePanelBillsLayout.createSequentialGroup()
                        .addComponent(lblBillsLogoText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        sidePanel.add(sidePanelBills, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 180, 40));

        sidePanelStorage.setBackground(new java.awt.Color(79, 88, 133));
        sidePanelStorage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidePanelElementsMousePressed(evt);
            }
        });

        lblStorageLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/storage30px.png"))); // NOI18N

        lblStorageLogoText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStorageLogoText.setForeground(new java.awt.Color(255, 255, 255));
        lblStorageLogoText.setText("label");

        javax.swing.GroupLayout sidePanelStorageLayout = new javax.swing.GroupLayout(sidePanelStorage);
        sidePanelStorage.setLayout(sidePanelStorageLayout);
        sidePanelStorageLayout.setHorizontalGroup(
            sidePanelStorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelStorageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStorageLogo1)
                .addGap(18, 18, 18)
                .addGroup(sidePanelStorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelStorageLayout.createSequentialGroup()
                        .addComponent(lblStorageLogoText)
                        .addGap(90, 90, 90))
                    .addComponent(jSeparator5))
                .addContainerGap())
        );
        sidePanelStorageLayout.setVerticalGroup(
            sidePanelStorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelStorageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStorageLogoText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblStorageLogo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(sidePanelStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 180, 40));

        sidePanelWorkers.setBackground(new java.awt.Color(79, 88, 133));
        sidePanelWorkers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidePanelElementsMousePressed(evt);
            }
        });

        lblWorkersLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin30px.png"))); // NOI18N

        lblWorkersLogoText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblWorkersLogoText.setForeground(new java.awt.Color(255, 255, 255));
        lblWorkersLogoText.setText("label");

        javax.swing.GroupLayout sidePanelWorkersLayout = new javax.swing.GroupLayout(sidePanelWorkers);
        sidePanelWorkers.setLayout(sidePanelWorkersLayout);
        sidePanelWorkersLayout.setHorizontalGroup(
            sidePanelWorkersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelWorkersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWorkersLogo)
                .addGap(18, 18, 18)
                .addGroup(sidePanelWorkersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelWorkersLayout.createSequentialGroup()
                        .addComponent(lblWorkersLogoText)
                        .addGap(90, 90, 90))
                    .addComponent(jSeparator6))
                .addContainerGap())
        );
        sidePanelWorkersLayout.setVerticalGroup(
            sidePanelWorkersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelWorkersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWorkersLogoText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblWorkersLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(sidePanelWorkers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 180, 40));

        panelBackground.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 650));

        horizontalPanel.setBackground(new java.awt.Color(79, 88, 133));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("label:");

        javax.swing.GroupLayout horizontalPanelLayout = new javax.swing.GroupLayout(horizontalPanel);
        horizontalPanel.setLayout(horizontalPanelLayout);
        horizontalPanelLayout.setHorizontalGroup(
            horizontalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(horizontalPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(418, Short.MAX_VALUE))
        );
        horizontalPanelLayout.setVerticalGroup(
            horizontalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(horizontalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBackground.add(horizontalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 830, 80));

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 60, 126)));

        layeredPane.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelClientsLayout = new javax.swing.GroupLayout(panelClients);
        panelClients.setLayout(panelClientsLayout);
        panelClientsLayout.setHorizontalGroup(
            panelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchClient, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        panelClientsLayout.setVerticalGroup(
            panelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchClient, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelMedicalRecordsLayout = new javax.swing.GroupLayout(panelMedicalRecords);
        panelMedicalRecords.setLayout(panelMedicalRecordsLayout);
        panelMedicalRecordsLayout.setHorizontalGroup(
            panelMedicalRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchMedicalRecords, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        panelMedicalRecordsLayout.setVerticalGroup(
            panelMedicalRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchMedicalRecords, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBillsLayout = new javax.swing.GroupLayout(panelBills);
        panelBills.setLayout(panelBillsLayout);
        panelBillsLayout.setHorizontalGroup(
            panelBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchBill, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        panelBillsLayout.setVerticalGroup(
            panelBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchBill, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelStorageLayout = new javax.swing.GroupLayout(panelStorage);
        panelStorage.setLayout(panelStorageLayout);
        panelStorageLayout.setHorizontalGroup(
            panelStorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchObjectOfSale, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        panelStorageLayout.setVerticalGroup(
            panelStorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchObjectOfSale, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelWorkersLayout = new javax.swing.GroupLayout(panelWorkers);
        panelWorkers.setLayout(panelWorkersLayout);
        panelWorkersLayout.setHorizontalGroup(
            panelWorkersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchWorker, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        panelWorkersLayout.setVerticalGroup(
            panelWorkersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSearchWorker, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        layeredPane.setLayer(panelClients, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPane.setLayer(panelMedicalRecords, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPane.setLayer(panelBills, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPane.setLayer(panelStorage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPane.setLayer(panelWorkers, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layeredPaneLayout = new javax.swing.GroupLayout(layeredPane);
        layeredPane.setLayout(layeredPaneLayout);
        layeredPaneLayout.setHorizontalGroup(
            layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredPaneLayout.createSequentialGroup()
                .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layeredPaneLayout.createSequentialGroup()
                        .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelMedicalRecords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelStorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelBills, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredPaneLayout.createSequentialGroup()
                    .addContainerGap(26, Short.MAX_VALUE)
                    .addComponent(panelWorkers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layeredPaneLayout.setVerticalGroup(
            layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredPaneLayout.createSequentialGroup()
                .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMedicalRecords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelStorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredPaneLayout.createSequentialGroup()
                .addComponent(panelClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layeredPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelWorkers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        scrollPane.setViewportView(layeredPane);

        panelBackground.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 780, 470));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete30px.png"))); // NOI18N
        btnDelete.setOpaque(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        panelBackground.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 610, -1, -1));

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit30px.png"))); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        panelBackground.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 610, -1, -1));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add30px.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panelBackground.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 610, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sidePanelElementsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePanelElementsMousePressed
        scrollPane.setVisible(true);
        if (evt.getSource() == sidePanelStorage) {
            setColor(sidePanelStorage);
            resetColor(sidePanelExit);
            resetColor(sidePanelBills);
            resetColor(sidePanelMedicalReports);
            resetColor(sidePanelClients);
            resetColor(sidePanelWorkers);

            activePanel = panelStorage;
            unhidePanel(panelStorage);
            hidePanel(panelBills);
            hidePanel(panelClients);
            hidePanel(panelMedicalRecords);
            hidePanel(panelWorkers);

            setTitleText("Rad sa: skladištem");

        }
        if (evt.getSource() == sidePanelBills) {
            setColor(sidePanelBills);
            resetColor(sidePanelExit);
            resetColor(sidePanelMedicalReports);
            resetColor(sidePanelClients);
            resetColor(sidePanelStorage);
            resetColor(sidePanelWorkers);

            activePanel = panelBills;
            unhidePanel(panelBills);
            hidePanel(panelStorage);
            hidePanel(panelClients);
            hidePanel(panelMedicalRecords);
            hidePanel(panelWorkers);

            setTitleText("Rad sa: računima");

        }
        if (evt.getSource() == sidePanelMedicalReports) {
            setColor(sidePanelMedicalReports);
            resetColor(sidePanelBills);
            resetColor(sidePanelExit);
            resetColor(sidePanelClients);
            resetColor(sidePanelStorage);
            resetColor(sidePanelWorkers);

            activePanel = panelMedicalRecords;
            unhidePanel(panelMedicalRecords);
            hidePanel(panelStorage);
            hidePanel(panelClients);
            hidePanel(panelStorage);
            hidePanel(panelWorkers);

            setTitleText("Rad sa: kartonima");
        }
        if (evt.getSource() == sidePanelClients) {
            setColor(sidePanelClients);
            resetColor(sidePanelBills);
            resetColor(sidePanelMedicalReports);
            resetColor(sidePanelExit);
            resetColor(sidePanelStorage);
            resetColor(sidePanelWorkers);

            activePanel = panelClients;
            unhidePanel(panelClients);
            hidePanel(panelBills);
            hidePanel(panelStorage);
            hidePanel(panelMedicalRecords);
            hidePanel(panelWorkers);

            setTitleText("Rad sa: klijentima");

        }

        if (evt.getSource() == sidePanelWorkers) {
            setColor(sidePanelWorkers);
            resetColor(sidePanelBills);
            resetColor(sidePanelMedicalReports);
            resetColor(sidePanelExit);
            resetColor(sidePanelStorage);
            resetColor(sidePanelClients);

            activePanel = panelWorkers;
            unhidePanel(panelWorkers);
            hidePanel(panelBills);
            hidePanel(panelClients);
            hidePanel(panelStorage);
            hidePanel(panelMedicalRecords);

            setTitleText("Rad sa: radnicima");

        }
        if (evt.getSource() == sidePanelExit) {
            setColor(sidePanelExit);
            resetColor(sidePanelBills);
            resetColor(sidePanelMedicalReports);
            resetColor(sidePanelClients);
            resetColor(sidePanelStorage);
            resetColor(sidePanelWorkers);

            System.exit(0);

            setTitleText("");
        }
    }//GEN-LAST:event_sidePanelElementsMousePressed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (activePanel == panelClients) {
            new DialogAddClient(this, true).setVisible(true);

        }
        if (activePanel == panelMedicalRecords) {
            new DialogAddMedicalRecord(radnik).setVisible(true);

        }
        if (activePanel == panelWorkers) {
            new DialogAddWorker(this, true).setVisible(true);

        }
        if (activePanel == panelBills) {
            new DialogAddBill((Frame) SwingUtilities.getWindowAncestor(this), true).setVisible(true);

        }
        if (activePanel == panelStorage) {
            new DialogAddStorage(this, rootPaneCheckingEnabled).setVisible(true);
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (activePanel == panelClients) {
            new DialogEditClient(this, false, (Klijent) panelSearchClient.getValue()).setVisible(true);
        }
        if (activePanel == panelMedicalRecords) {
            new DialogEditMedicalRecord(this, true, (Karton) panelSearchMedicalRecords.getValue()).setVisible(true);
        }
        if (activePanel == panelWorkers) {
            new DialogEditWorker(this, true, (Radnik) panelSearchWorker.getValue()).setVisible(true);
        }
        if (activePanel == panelBills) {
            btnEdit.setEnabled(false);
            btnDelete.setEnabled(false);
        }

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (activePanel == panelClients) {
            try {
                panelSearchClient.removeObject((Klijent) panelSearchClient.getValue());
            } catch (Exception ex) {
                Logger.getLogger(FrmMainWork.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (activePanel == panelBills) {
            try {
                panelSearchBill.removeObject((DomainObject) panelSearchBill.getValue());
            } catch (Exception ex) {
                Logger.getLogger(FrmMainWork.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (activePanel == panelWorkers) {
            try {
                panelSearchWorker.removeObject((DomainObject) panelSearchWorker.getValue());
            } catch (Exception ex) {
                Logger.getLogger(FrmMainWork.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (activePanel == panelMedicalRecords) {
            try {
                panelSearchMedicalRecords.removeObject((DomainObject) panelSearchMedicalRecords.getValue());
            } catch (Exception ex) {
                Logger.getLogger(FrmMainWork.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (activePanel == panelStorage) {
            try {
                panelSearchObjectOfSale.removeObject((DomainObject) panelSearchObjectOfSale.getValue());
            } catch (Exception ex) {
                Logger.getLogger(FrmMainWork.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JPanel horizontalPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JLabel lblBillsLogo;
    private javax.swing.JLabel lblBillsLogoText;
    private javax.swing.JLabel lblClientsLogo;
    private javax.swing.JLabel lblClientsLogoText;
    private javax.swing.JLabel lblExitLogo;
    private javax.swing.JLabel lblExitLogoText;
    private javax.swing.JLabel lblMedicalReportsLogo;
    private javax.swing.JLabel lblMedicalReportsLogoText;
    private javax.swing.JLabel lblStorageLogo1;
    private javax.swing.JLabel lblStorageLogoText;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWorkerLogo;
    private javax.swing.JLabel lblWorkerName;
    private javax.swing.JLabel lblWorkersLogo;
    private javax.swing.JLabel lblWorkersLogoText;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBills;
    private javax.swing.JPanel panelClients;
    private javax.swing.JPanel panelMedicalRecords;
    private view.panel.custom.PanelSearchBill panelSearchBill;
    private view.panel.custom.PanelSearchClient panelSearchClient;
    private view.panel.custom.PanelSearchMedicalRecords panelSearchMedicalRecords;
    private view.panel.custom.PanelSearchObjectOfSale panelSearchObjectOfSale;
    private view.panel.custom.PanelSearchWorker panelSearchWorker;
    private javax.swing.JPanel panelStorage;
    private javax.swing.JPanel panelWorkers;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel sidePanelBills;
    private javax.swing.JPanel sidePanelClients;
    private javax.swing.JPanel sidePanelExit;
    private javax.swing.JPanel sidePanelMedicalReports;
    private javax.swing.JPanel sidePanelStorage;
    private javax.swing.JPanel sidePanelWorkers;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        setPanelStates();
        setSidePanelElements();
        setProjectIcon();
        preparePanels();
        setTitleText("Dobrodosli!");
    }

    private void setSidePanelElements() {

        lblClientsLogoText.setText("Klijenti");

        lblMedicalReportsLogoText.setText("Kartoni");

        lblBillsLogoText.setText("Računi");

        lblStorageLogoText.setText("Skladište");

        lblWorkersLogoText.setText("Radnici");

        lblExitLogoText.setText("Kraj rada");

        lblWorkerName.setText("Radnik: " + radnik.toString());

    }

    void setColor(JPanel panel) {
        panel.setBackground(new Color(85, 65, 118));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(79, 88, 133));
    }

    private void setProjectIcon() {
        URL imageUrl = ClassLoader.getSystemResource("img/logoLogin95px.png");
        ImageIcon imageIcon = new ImageIcon(imageUrl);
        setIconImage(imageIcon.getImage());
    }

    private void unhidePanel(JPanel panel) {
        panel.setVisible(true);
    }

    private void hidePanel(JPanel panel) {
        panel.setVisible(false);
    }

    private void setTitleText(String text) {
        lblTitle.setText(text);
    }

    private void setPanelStates() {
        hidePanel(panelBills);
        hidePanel(panelWorkers);
        hidePanel(panelMedicalRecords);
        hidePanel(panelStorage);
        hidePanel(panelClients);
        scrollPane.setVisible(false);
    }

    private void preparePanels() {
        panelSearchClient.preparePanel();
        panelSearchMedicalRecords.preparePanel();
        panelSearchWorker.preparePanel();
        panelSearchBill.preparePanel();
        panelSearchObjectOfSale.preparePanel();
    }

}
